/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project_001_hris;

import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JToggleButton;
import javax.swing.SwingWorker;

/**
 *
 * @author Web Dev
 */
public class DialogSettings extends javax.swing.JDialog {

    ImageIcon icon = new javax.swing.ImageIcon(getClass().getResource("/img_src/icon_16_gear_in.png"));
    ClassConstantVariables constant = new ClassConstantVariables();

    /**
     * Creates new form DialogSettings
     */
    public DialogSettings(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        getMainLayout().show(dialogSettingPanel, "Card Load");
        getMainLayout().show(dialogSettingPanel, "Card Open");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        settingButtonGroup = new javax.swing.ButtonGroup();
        dialogPopup = new javax.swing.JDialog();
        dialogPopupPanel = new javax.swing.JPanel();
        dialogSettingsBtn = new javax.swing.JPanel();
        toolBar = new javax.swing.JToolBar();
        panelTooBar = new javax.swing.JPanel();
        tglBtnCat = new javax.swing.JToggleButton();
        tglBtnElg = new javax.swing.JToggleButton();
        tglBtnOfc = new javax.swing.JToggleButton();
        tglBtnPos = new javax.swing.JToggleButton();
        tglBtnTrn = new javax.swing.JToggleButton();
        dialogSettingPanel = new javax.swing.JPanel();
        panelOpen = new javax.swing.JPanel();
        panelOpenLogo = new javax.swing.JLabel();
        panelOpenText = new javax.swing.JLabel();
        panelLoading = new javax.swing.JPanel();
        labelLoadingLogo = new javax.swing.JLabel();
        labelLoadingText = new javax.swing.JLabel();
        panelMain = new javax.swing.JPanel();

        dialogPopup.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        dialogPopup.setModal(true);
        dialogPopup.setResizable(false);
        dialogPopup.setType(java.awt.Window.Type.POPUP);

        dialogPopupPanel.setLayout(new java.awt.CardLayout(10, 5));
        dialogPopup.getContentPane().add(dialogPopupPanel, java.awt.BorderLayout.CENTER);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Form Manager Settings");
        setIconImage(icon.getImage());
        setModal(true);
        setResizable(false);

        dialogSettingsBtn.setBackground(new java.awt.Color(230, 230, 230));
        dialogSettingsBtn.setPreferredSize(new java.awt.Dimension(100, 201));
        dialogSettingsBtn.setLayout(new java.awt.BorderLayout());

        toolBar.setFloatable(false);
        toolBar.setOrientation(javax.swing.SwingConstants.VERTICAL);
        toolBar.setRollover(true);
        toolBar.setOpaque(false);
        toolBar.setPreferredSize(new java.awt.Dimension(75, 25));

        panelTooBar.setMinimumSize(new java.awt.Dimension(10, 15));
        panelTooBar.setOpaque(false);
        panelTooBar.setPreferredSize(new java.awt.Dimension(5, 5));
        toolBar.add(panelTooBar);

        settingButtonGroup.add(tglBtnCat);
        tglBtnCat.setFont(new java.awt.Font("Century Gothic", 3, 10)); // NOI18N
        tglBtnCat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_src/icon_16_table_gear.png"))); // NOI18N
        tglBtnCat.setText("<html><center>Category<br />Manager</html>");
        tglBtnCat.setFocusable(false);
        tglBtnCat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tglBtnCat.setPreferredSize(new java.awt.Dimension(85, 80));
        tglBtnCat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tglBtnCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglBtnCatActionPerformed(evt);
            }
        });
        toolBar.add(tglBtnCat);

        settingButtonGroup.add(tglBtnElg);
        tglBtnElg.setFont(new java.awt.Font("Century Gothic", 3, 10)); // NOI18N
        tglBtnElg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_src/icon_16_table_gear.png"))); // NOI18N
        tglBtnElg.setText("<html><center>Eligibility<br />Manager</html>");
        tglBtnElg.setFocusable(false);
        tglBtnElg.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tglBtnElg.setPreferredSize(new java.awt.Dimension(85, 80));
        tglBtnElg.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tglBtnElg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglBtnElgActionPerformed(evt);
            }
        });
        toolBar.add(tglBtnElg);

        settingButtonGroup.add(tglBtnOfc);
        tglBtnOfc.setFont(new java.awt.Font("Century Gothic", 3, 10)); // NOI18N
        tglBtnOfc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_src/icon_16_table_gear.png"))); // NOI18N
        tglBtnOfc.setText("<html><center>Office<br />Manager</html>");
        tglBtnOfc.setFocusable(false);
        tglBtnOfc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tglBtnOfc.setPreferredSize(new java.awt.Dimension(85, 80));
        tglBtnOfc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tglBtnOfc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglBtnOfcActionPerformed(evt);
            }
        });
        toolBar.add(tglBtnOfc);

        settingButtonGroup.add(tglBtnPos);
        tglBtnPos.setFont(new java.awt.Font("Century Gothic", 3, 10)); // NOI18N
        tglBtnPos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_src/icon_16_table_gear.png"))); // NOI18N
        tglBtnPos.setText("<html><center>Position<br />Manager</html>");
        tglBtnPos.setFocusable(false);
        tglBtnPos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tglBtnPos.setPreferredSize(new java.awt.Dimension(85, 80));
        tglBtnPos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tglBtnPos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglBtnPosActionPerformed(evt);
            }
        });
        toolBar.add(tglBtnPos);

        settingButtonGroup.add(tglBtnTrn);
        tglBtnTrn.setFont(new java.awt.Font("Century Gothic", 3, 10)); // NOI18N
        tglBtnTrn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_src/icon_16_table_gear.png"))); // NOI18N
        tglBtnTrn.setText("<html><center>Training<br />Manager</html>");
        tglBtnTrn.setFocusable(false);
        tglBtnTrn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tglBtnTrn.setPreferredSize(new java.awt.Dimension(85, 80));
        tglBtnTrn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tglBtnTrn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglBtnTrnActionPerformed(evt);
            }
        });
        toolBar.add(tglBtnTrn);

        dialogSettingsBtn.add(toolBar, java.awt.BorderLayout.CENTER);

        getContentPane().add(dialogSettingsBtn, java.awt.BorderLayout.LINE_START);

        dialogSettingPanel.setLayout(new java.awt.CardLayout());

        panelOpen.setBackground(new java.awt.Color(245, 245, 245));
        panelOpen.setLayout(new java.awt.GridBagLayout());

        panelOpenLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelOpenLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_src/loading_48_gear_02.png"))); // NOI18N
        panelOpenLogo.setLabelFor(dialogSettingsBtn);
        panelOpenLogo.setToolTipText("");
        panelOpen.add(panelOpenLogo, new java.awt.GridBagConstraints());

        panelOpenText.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        panelOpenText.setForeground(new java.awt.Color(130, 130, 130));
        panelOpenText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelOpenText.setLabelFor(dialogSettingsBtn);
        panelOpenText.setText("Choose a settings");
        panelOpenText.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        panelOpen.add(panelOpenText, gridBagConstraints);

        dialogSettingPanel.add(panelOpen, "Card Open");

        panelLoading.setBackground(new java.awt.Color(245, 245, 245));
        panelLoading.setLayout(new java.awt.GridBagLayout());

        labelLoadingLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelLoadingLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_src/loading_48_gear_02.gif"))); // NOI18N
        labelLoadingLogo.setLabelFor(dialogSettingsBtn);
        labelLoadingLogo.setToolTipText("");
        panelLoading.add(labelLoadingLogo, new java.awt.GridBagConstraints());

        labelLoadingText.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        labelLoadingText.setForeground(new java.awt.Color(130, 130, 130));
        labelLoadingText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelLoadingText.setLabelFor(dialogSettingsBtn);
        labelLoadingText.setText("loading...");
        labelLoadingText.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        panelLoading.add(labelLoadingText, gridBagConstraints);

        dialogSettingPanel.add(panelLoading, "Card Load");

        panelMain.setLayout(new java.awt.CardLayout());
        dialogSettingPanel.add(panelMain, "Card Main");

        getContentPane().add(dialogSettingPanel, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(616, 449));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tglBtnElgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglBtnElgActionPerformed

        getMainLayout().show(dialogSettingPanel, "Card Load");

        loadPanel(new project_001_hris.PanelSettingsEligibility(), constant.PANEL_FRAME, tglBtnElg);

    }//GEN-LAST:event_tglBtnElgActionPerformed

    private void tglBtnCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglBtnCatActionPerformed

        getMainLayout().show(dialogSettingPanel, "Card Load");

        loadPanel(new project_001_hris.PanelSettingsCategory(), constant.PANEL_FRAME, tglBtnCat);

    }//GEN-LAST:event_tglBtnCatActionPerformed

    private void tglBtnOfcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglBtnOfcActionPerformed
        
        getMainLayout().show(dialogSettingPanel, "Card Load");

        loadPanel(new project_001_hris.PanelSettingsOffice(), constant.PANEL_FRAME, tglBtnOfc);

    }//GEN-LAST:event_tglBtnOfcActionPerformed

    private void tglBtnPosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglBtnPosActionPerformed

        getMainLayout().show(dialogSettingPanel, "Card Load");

        loadPanel(new project_001_hris.PanelSettingsPosition(), constant.PANEL_FRAME, tglBtnPos);

    }//GEN-LAST:event_tglBtnPosActionPerformed

    private void tglBtnTrnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglBtnTrnActionPerformed

        getMainLayout().show(dialogSettingPanel, "Card Load");

        loadPanel(new project_001_hris.PanelSettingsTraining(), constant.PANEL_FRAME, tglBtnTrn);

    }//GEN-LAST:event_tglBtnTrnActionPerformed

    public void setButtons(Boolean bool, JToggleButton tButton, Boolean bool2) {
        
        tglBtnCat.setEnabled(bool);
        tglBtnElg.setEnabled(bool);
        tglBtnOfc.setEnabled(bool);
        tglBtnPos.setEnabled(bool);
        tglBtnTrn.setEnabled(bool);

        if (bool == true) {
            tglBtnCat.setForeground(new Color(25, 25, 25));
            tglBtnElg.setForeground(new Color(25, 25, 25));
            tglBtnOfc.setForeground(new Color(25, 25, 25));
            tglBtnPos.setForeground(new Color(25, 25, 25));
            tglBtnTrn.setForeground(new Color(25, 25, 25));
        } else {
            tglBtnCat.setForeground(new Color(125, 125, 125));
            tglBtnElg.setForeground(new Color(125, 125, 125));
            tglBtnOfc.setForeground(new Color(125, 125, 125));
            tglBtnPos.setForeground(new Color(125, 125, 125));
            tglBtnTrn.setForeground(new Color(125, 125, 125));
        }

        if(bool2 == true)
            tButton.setSelected(true);
        else
            tButton.setSelected(false);

    }

    /**
     * 
     * @param panel
     * @param type frame(1) or pop-up(2)
     * @param tButton 
     */
    public void loadPanel(final JPanel panel, final int type, final JToggleButton tButton) {

        setButtons(false, tButton, true);

        final CardLayout mainLayout = (CardLayout) dialogSettingPanel.getLayout();        
        
        @SuppressWarnings("unchecked")
                
        SwingWorker<Void, Void> sw = new SwingWorker() {

            @Override
            protected Object doInBackground() throws Exception {

                mainLayout.show(dialogSettingPanel, "Card Load");
                labelLoadingText.setText("loading...");
                
                try {
                    if (type == constant.PANEL_FRAME){
                        if (panelFrame == null || panelFrame.isVisible()) {
                            
                            panelMain.removeAll();
                            panelFrame = panel;
                            panelMain.add(panelFrame);
                            labelLoadingText.setText("preparing...");

                        } 
                    } else if (type == constant.PANEL_POPUP){
                        if (panelPopup == null || panelPopup.isVisible()) {
                            
                            dialogPopupPanel.removeAll();
                            panelPopup = panel;
                            dialogPopupPanel.add(panelPopup);
                            labelLoadingText.setText("preparing...");
                            
                        } 
                    }
                    
                } catch (Exception ex) {
                    labelLoadingText.setText("failed loading...");
                    System.out.println(ex.getMessage());
                    JOptionPane.showMessageDialog(null, "Error Occured When Loading", "ERROR!", JOptionPane.ERROR_MESSAGE);
                }

                labelLoadingText.setText("initializing...");

                return null;
            }

            @Override
            protected void done() {
                new java.util.Timer().schedule(
                    new java.util.TimerTask() {
                        @Override
                        public void run() {
                            labelLoadingText.setText("complete.");
                            mainLayout.show(dialogSettingPanel, "Card Main");

                            setButtons(true, tButton, true);

                        }
                    },
                    1000
                );
            }

        };

        sw.execute();

    }
    
    private CardLayout getMainLayout() {
        CardLayout mainLayout = (CardLayout) dialogSettingPanel.getLayout();
        return mainLayout;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                DialogSettings dialog = new DialogSettings(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog dialogPopup;
    private javax.swing.JPanel dialogPopupPanel;
    private javax.swing.JPanel dialogSettingPanel;
    private javax.swing.JPanel dialogSettingsBtn;
    private javax.swing.JLabel labelLoadingLogo;
    private javax.swing.JLabel labelLoadingText;
    private javax.swing.JPanel panelLoading;
    private javax.swing.JPanel panelMain;
    private javax.swing.JPanel panelOpen;
    private javax.swing.JLabel panelOpenLogo;
    private javax.swing.JLabel panelOpenText;
    private javax.swing.JPanel panelTooBar;
    private javax.swing.ButtonGroup settingButtonGroup;
    private javax.swing.JToggleButton tglBtnCat;
    private javax.swing.JToggleButton tglBtnElg;
    private javax.swing.JToggleButton tglBtnOfc;
    private javax.swing.JToggleButton tglBtnPos;
    private javax.swing.JToggleButton tglBtnTrn;
    private javax.swing.JToolBar toolBar;
    // End of variables declaration//GEN-END:variables

    private JPanel panelFrame;
    private JPanel panelPopup;

}
