/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package project_001_hris;

import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JProgressBar;
import javax.swing.JToggleButton;
import javax.swing.SwingWorker;

/**
 *
 * @author Blacqueous
 */
public class FrameMain extends javax.swing.JFrame {
    
    ImageIcon icon = new javax.swing.ImageIcon(getClass().getResource("/img_src/icon_16_logo_hris.png"));
    ClassConstantVariables constant = new ClassConstantVariables();
    Boolean bool = false;
    String frameString = "";
    
    /**
     * Creates new form Frame_main
     */
    public FrameMain() {
        initComponents();
        menuCheckBoxMax.setState(bool);
        getMainLayout().show(panelCenter, "Card Center Open");
        tglBtnHome.setSelected(true);
        closeProgram();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngrpToolBar = new javax.swing.ButtonGroup();
        dialogPopup = new javax.swing.JDialog();
        dialogPopupPanelC = new javax.swing.JPanel();
        dialogPopupPanelL = new javax.swing.JPanel();
        dialogPopupPanelR = new javax.swing.JPanel();
        dialogPopupPanelT = new javax.swing.JPanel();
        panelToolbar = new javax.swing.JPanel();
        toolBar = new javax.swing.JToolBar();
        toolBarLabel = new javax.swing.JLabel();
        tglBtnHome = new javax.swing.JToggleButton();
        jSeparator = new javax.swing.JToolBar.Separator();
        tglBtnSearch = new javax.swing.JToggleButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        tglBtnCreate = new javax.swing.JToggleButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        tglBtnUpdate = new javax.swing.JToggleButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        tglBtnDelete = new javax.swing.JToggleButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        tglBtnPrint = new javax.swing.JToggleButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        panelCenter = new javax.swing.JPanel();
        panelCenterLoad = new javax.swing.JPanel();
        lblCenterLoad = new javax.swing.JLabel();
        panelCenterOpen = new javax.swing.JPanel();
        lblCenterOpen = new javax.swing.JLabel();
        panelCenterMain = new javax.swing.JPanel();
        panelMain = new javax.swing.JPanel();
        panelMainBottom = new javax.swing.JPanel();
        mainSeparator = new javax.swing.JSeparator();
        lblAboutLogo = new javax.swing.JLabel();
        panelMainProgress = new javax.swing.JPanel();
        lblLoadingText = new javax.swing.JLabel();
        progressBar = new javax.swing.JProgressBar();
        menuBar = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        menuItemEmpCreate = new javax.swing.JMenuItem();
        menuItemLogOut = new javax.swing.JMenuItem();
        menuFileSeparator = new javax.swing.JPopupMenu.Separator();
        menuItemExit = new javax.swing.JMenuItem();
        menuTask = new javax.swing.JMenu();
        menuItemEmpSearch = new javax.swing.JMenuItem();
        menuTaskSeparator = new javax.swing.JPopupMenu.Separator();
        menuItemEmpUpdate = new javax.swing.JMenuItem();
        menuItemEmpDelete = new javax.swing.JMenuItem();
        menuItemEmpDeleteMany = new javax.swing.JMenuItem();
        menuTools = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        menuAccount = new javax.swing.JMenu();
        menuItemAccountManage = new javax.swing.JMenuItem();
        menuItemAccountCreate = new javax.swing.JMenuItem();
        menuAccountSeparator = new javax.swing.JPopupMenu.Separator();
        menuItemAccountManageAll = new javax.swing.JMenuItem();
        menuToolsSeparator = new javax.swing.JPopupMenu.Separator();
        menuItemRecycle = new javax.swing.JMenuItem();
        menuItemThemeColor = new javax.swing.JMenuItem();
        menuCheckBoxMax = new javax.swing.JCheckBoxMenuItem();
        menuHelp = new javax.swing.JMenu();
        menuItemStart = new javax.swing.JMenuItem();
        menuItemReport = new javax.swing.JMenuItem();
        menuHelpSeparator = new javax.swing.JPopupMenu.Separator();
        menuItemAbout = new javax.swing.JMenuItem();

        dialogPopup.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        dialogPopup.setModal(true);
        dialogPopup.setResizable(false);
        dialogPopup.setType(java.awt.Window.Type.POPUP);

        dialogPopupPanelC.setLayout(new java.awt.CardLayout(10, 5));
        dialogPopup.getContentPane().add(dialogPopupPanelC, java.awt.BorderLayout.CENTER);

        dialogPopupPanelL.setLayout(new java.awt.GridLayout(1, 0));
        dialogPopup.getContentPane().add(dialogPopupPanelL, java.awt.BorderLayout.LINE_START);

        dialogPopupPanelR.setLayout(new java.awt.GridLayout(1, 0));
        dialogPopup.getContentPane().add(dialogPopupPanelR, java.awt.BorderLayout.LINE_END);

        dialogPopupPanelT.setPreferredSize(new java.awt.Dimension(0, 5));
        dialogPopupPanelT.setLayout(new java.awt.GridLayout(1, 0));
        dialogPopup.getContentPane().add(dialogPopupPanelT, java.awt.BorderLayout.PAGE_START);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Human Resource Information System");
        setIconImage(icon.getImage());
        setMinimumSize(new java.awt.Dimension(1000, 700));

        panelToolbar.setBackground(new java.awt.Color(230, 230, 230));
        panelToolbar.setPreferredSize(new java.awt.Dimension(100, 85));
        panelToolbar.setLayout(new java.awt.BorderLayout());

        toolBar.setFloatable(false);
        toolBar.setRollover(true);
        toolBar.setOpaque(false);
        toolBar.setPreferredSize(new java.awt.Dimension(100, 75));

        toolBarLabel.setText("  ");
        toolBar.add(toolBarLabel);

        btngrpToolBar.add(tglBtnHome);
        tglBtnHome.setFont(new java.awt.Font("Century Gothic", 3, 11)); // NOI18N
        tglBtnHome.setForeground(new java.awt.Color(25, 25, 25));
        tglBtnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_src/icon_32_house_one.png"))); // NOI18N
        tglBtnHome.setText("Home");
        tglBtnHome.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/img_src/icon_32_user_search.png"))); // NOI18N
        tglBtnHome.setFocusable(false);
        tglBtnHome.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tglBtnHome.setPreferredSize(new java.awt.Dimension(80, 75));
        tglBtnHome.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tglBtnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglBtnHomeActionPerformed(evt);
            }
        });
        toolBar.add(tglBtnHome);
        toolBar.add(jSeparator);

        btngrpToolBar.add(tglBtnSearch);
        tglBtnSearch.setFont(new java.awt.Font("Century Gothic", 3, 11)); // NOI18N
        tglBtnSearch.setForeground(new java.awt.Color(25, 25, 25));
        tglBtnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_src/icon_32_user_search_color.png"))); // NOI18N
        tglBtnSearch.setText("Search");
        tglBtnSearch.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/img_src/icon_32_user_search_duo.png"))); // NOI18N
        tglBtnSearch.setFocusable(false);
        tglBtnSearch.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tglBtnSearch.setPreferredSize(new java.awt.Dimension(80, 75));
        tglBtnSearch.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tglBtnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglBtnSearchActionPerformed(evt);
            }
        });
        toolBar.add(tglBtnSearch);
        toolBar.add(jSeparator1);

        btngrpToolBar.add(tglBtnCreate);
        tglBtnCreate.setFont(new java.awt.Font("Century Gothic", 3, 11)); // NOI18N
        tglBtnCreate.setForeground(new java.awt.Color(25, 25, 25));
        tglBtnCreate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_src/icon_32_group_add.png"))); // NOI18N
        tglBtnCreate.setText("Create");
        tglBtnCreate.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/img_src/icon_32_group_add_duo.png"))); // NOI18N
        tglBtnCreate.setFocusable(false);
        tglBtnCreate.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tglBtnCreate.setPreferredSize(new java.awt.Dimension(80, 75));
        tglBtnCreate.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tglBtnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglBtnCreateActionPerformed(evt);
            }
        });
        toolBar.add(tglBtnCreate);
        toolBar.add(jSeparator2);

        btngrpToolBar.add(tglBtnUpdate);
        tglBtnUpdate.setFont(new java.awt.Font("Century Gothic", 3, 11)); // NOI18N
        tglBtnUpdate.setForeground(new java.awt.Color(25, 25, 25));
        tglBtnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_src/icon_32_group_edit.png"))); // NOI18N
        tglBtnUpdate.setText("Update");
        tglBtnUpdate.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/img_src/icon_32_group_edit_duo.png"))); // NOI18N
        tglBtnUpdate.setFocusable(false);
        tglBtnUpdate.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tglBtnUpdate.setPreferredSize(new java.awt.Dimension(80, 75));
        tglBtnUpdate.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolBar.add(tglBtnUpdate);
        toolBar.add(jSeparator3);

        btngrpToolBar.add(tglBtnDelete);
        tglBtnDelete.setFont(new java.awt.Font("Century Gothic", 3, 11)); // NOI18N
        tglBtnDelete.setForeground(new java.awt.Color(25, 25, 25));
        tglBtnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_src/icon_32_group_delete.png"))); // NOI18N
        tglBtnDelete.setText("Delete");
        tglBtnDelete.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/img_src/icon_32_group_delete_duo.png"))); // NOI18N
        tglBtnDelete.setFocusable(false);
        tglBtnDelete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tglBtnDelete.setPreferredSize(new java.awt.Dimension(80, 75));
        tglBtnDelete.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolBar.add(tglBtnDelete);
        toolBar.add(jSeparator4);

        btngrpToolBar.add(tglBtnPrint);
        tglBtnPrint.setFont(new java.awt.Font("Century Gothic", 3, 11)); // NOI18N
        tglBtnPrint.setForeground(new java.awt.Color(25, 25, 25));
        tglBtnPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_src/icon_32_printer_color.png"))); // NOI18N
        tglBtnPrint.setText("Print");
        tglBtnPrint.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/img_src/icon_32_printer.png"))); // NOI18N
        tglBtnPrint.setFocusable(false);
        tglBtnPrint.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tglBtnPrint.setPreferredSize(new java.awt.Dimension(80, 75));
        tglBtnPrint.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tglBtnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglBtnPrintActionPerformed(evt);
            }
        });
        toolBar.add(tglBtnPrint);
        toolBar.add(jSeparator5);

        panelToolbar.add(toolBar, java.awt.BorderLayout.CENTER);

        getContentPane().add(panelToolbar, java.awt.BorderLayout.PAGE_START);

        panelCenter.setLayout(new java.awt.CardLayout());

        panelCenterLoad.setBackground(new java.awt.Color(250, 250, 250));
        panelCenterLoad.setLayout(new java.awt.GridBagLayout());

        lblCenterLoad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_src/loading_220x183_hris.gif"))); // NOI18N
        panelCenterLoad.add(lblCenterLoad, new java.awt.GridBagConstraints());

        panelCenter.add(panelCenterLoad, "Card Center Load");

        panelCenterOpen.setBackground(new java.awt.Color(250, 250, 250));
        panelCenterOpen.setLayout(new java.awt.GridBagLayout());

        lblCenterOpen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_src/loading_220x183_hris_open.gif"))); // NOI18N
        panelCenterOpen.add(lblCenterOpen, new java.awt.GridBagConstraints());

        panelCenter.add(panelCenterOpen, "Card Center Open");

        panelCenterMain.setLayout(new java.awt.BorderLayout());

        panelMain.setLayout(new java.awt.CardLayout(25, 10));
        panelCenterMain.add(panelMain, java.awt.BorderLayout.CENTER);

        panelCenter.add(panelCenterMain, "Card Center Main");

        getContentPane().add(panelCenter, java.awt.BorderLayout.CENTER);

        panelMainBottom.setPreferredSize(new java.awt.Dimension(10, 33));
        panelMainBottom.setLayout(new java.awt.BorderLayout());
        panelMainBottom.add(mainSeparator, java.awt.BorderLayout.PAGE_START);

        lblAboutLogo.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        lblAboutLogo.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblAboutLogo.setToolTipText("Powered by E.Graphix");
        lblAboutLogo.setPreferredSize(new java.awt.Dimension(36, 25));
        panelMainBottom.add(lblAboutLogo, java.awt.BorderLayout.LINE_START);

        panelMainProgress.setPreferredSize(new java.awt.Dimension(110, 33));
        panelMainProgress.setLayout(new java.awt.BorderLayout());

        lblLoadingText.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        lblLoadingText.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblLoadingText.setPreferredSize(new java.awt.Dimension(5, 0));
        panelMainProgress.add(lblLoadingText, java.awt.BorderLayout.LINE_END);

        progressBar.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        progressBar.setPreferredSize(new java.awt.Dimension(100, 10));
        progressBar.setString("Waiting");
        progressBar.setStringPainted(true);
        panelMainProgress.add(progressBar, java.awt.BorderLayout.CENTER);

        panelMainBottom.add(panelMainProgress, java.awt.BorderLayout.LINE_END);

        getContentPane().add(panelMainBottom, java.awt.BorderLayout.PAGE_END);

        menuFile.setMnemonic('f');
        menuFile.setText("  File  ");
        menuFile.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N

        menuItemEmpCreate.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        menuItemEmpCreate.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        menuItemEmpCreate.setMnemonic('c');
        menuItemEmpCreate.setText("Create Employee Data");
        menuFile.add(menuItemEmpCreate);

        menuItemLogOut.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_MASK));
        menuItemLogOut.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        menuItemLogOut.setMnemonic('l');
        menuItemLogOut.setText("Log Out");
        menuItemLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemLogOutActionPerformed(evt);
            }
        });
        menuFile.add(menuItemLogOut);
        menuFile.add(menuFileSeparator);

        menuItemExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.ALT_MASK));
        menuItemExit.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        menuItemExit.setMnemonic('x');
        menuItemExit.setText("Exit");
        menuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemExitActionPerformed(evt);
            }
        });
        menuFile.add(menuItemExit);

        menuBar.add(menuFile);

        menuTask.setMnemonic('t');
        menuTask.setText("  Task  ");
        menuTask.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N

        menuItemEmpSearch.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        menuItemEmpSearch.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        menuItemEmpSearch.setMnemonic('s');
        menuItemEmpSearch.setText("Search Employee Data");
        menuTask.add(menuItemEmpSearch);
        menuTask.add(menuTaskSeparator);

        menuItemEmpUpdate.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK));
        menuItemEmpUpdate.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        menuItemEmpUpdate.setMnemonic('e');
        menuItemEmpUpdate.setText("Update Employee Data");
        menuItemEmpUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemEmpUpdateActionPerformed(evt);
            }
        });
        menuTask.add(menuItemEmpUpdate);

        menuItemEmpDelete.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_MASK));
        menuItemEmpDelete.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        menuItemEmpDelete.setMnemonic('d');
        menuItemEmpDelete.setText("Delete Employee Data");
        menuItemEmpDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemEmpDeleteActionPerformed(evt);
            }
        });
        menuTask.add(menuItemEmpDelete);

        menuItemEmpDeleteMany.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK));
        menuItemEmpDeleteMany.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        menuItemEmpDeleteMany.setMnemonic('d');
        menuItemEmpDeleteMany.setText("Delete Multiple Employee Data");
        menuItemEmpDeleteMany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemEmpDeleteManyActionPerformed(evt);
            }
        });
        menuTask.add(menuItemEmpDeleteMany);

        menuBar.add(menuTask);

        menuTools.setMnemonic('o');
        menuTools.setText("  Tools  ");
        menuTools.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jMenuItem1.setText("Form Manager Settings");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuTools.add(jMenuItem1);

        menuAccount.setMnemonic('a');
        menuAccount.setText("Account Settings");
        menuAccount.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        menuItemAccountManage.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK));
        menuItemAccountManage.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        menuItemAccountManage.setMnemonic('u');
        menuItemAccountManage.setText("Manage User");
        menuAccount.add(menuItemAccountManage);

        menuItemAccountCreate.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        menuItemAccountCreate.setMnemonic('n');
        menuItemAccountCreate.setText("Create New User");
        menuAccount.add(menuItemAccountCreate);
        menuAccount.add(menuAccountSeparator);

        menuItemAccountManageAll.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        menuItemAccountManageAll.setMnemonic('a');
        menuItemAccountManageAll.setText("Manage All Users");
        menuAccount.add(menuItemAccountManageAll);

        menuTools.add(menuAccount);
        menuTools.add(menuToolsSeparator);

        menuItemRecycle.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        menuItemRecycle.setMnemonic('r');
        menuItemRecycle.setText("Recycle Employee Data");
        menuTools.add(menuItemRecycle);

        menuItemThemeColor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.ALT_MASK));
        menuItemThemeColor.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        menuItemThemeColor.setMnemonic('t');
        menuItemThemeColor.setText("Change Theme Color");
        menuTools.add(menuItemThemeColor);

        menuCheckBoxMax.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        menuCheckBoxMax.setMnemonic('m');
        menuCheckBoxMax.setSelected(true);
        menuCheckBoxMax.setText("Maximize Window");
        menuCheckBoxMax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCheckBoxMaxActionPerformed(evt);
            }
        });
        menuTools.add(menuCheckBoxMax);

        menuBar.add(menuTools);

        menuHelp.setText("  Help  ");
        menuHelp.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N

        menuItemStart.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        menuItemStart.setMnemonic('s');
        menuItemStart.setText("Start Page");
        menuHelp.add(menuItemStart);

        menuItemReport.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.ALT_MASK));
        menuItemReport.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        menuItemReport.setMnemonic('r');
        menuItemReport.setText("Report Issue");
        menuHelp.add(menuItemReport);
        menuHelp.add(menuHelpSeparator);

        menuItemAbout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK));
        menuItemAbout.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        menuItemAbout.setMnemonic('a');
        menuItemAbout.setText("About");
        menuHelp.add(menuItemAbout);

        menuBar.add(menuHelp);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuCheckBoxMaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCheckBoxMaxActionPerformed
        
        System.out.println(menuCheckBoxMax.getState() + "");
        
    }//GEN-LAST:event_menuCheckBoxMaxActionPerformed

    private void tglBtnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglBtnSearchActionPerformed
        
        if(!frameString.equals(constant.FRAME_EMP_SEARCH)) {
            progressBar.setIndeterminate(true);
            progressBar.setString("Calling");
            
            loadPanel(new project_001_hris.PanelFrameSearch(), constant.PANEL_FRAME, tglBtnSearch);
            
            frameString = constant.FRAME_EMP_SEARCH;
        }
        
    }//GEN-LAST:event_tglBtnSearchActionPerformed

    private void tglBtnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglBtnCreateActionPerformed
        
        if(!frameString.equals(constant.FRAME_EMP_CREATE)) {
            progressBar.setIndeterminate(true);
            progressBar.setString("Calling");
            
            project_001_hris.PanelFrameCreate panelFrameCreate = new project_001_hris.PanelFrameCreate();
            panelFrameCreate.setFrame(this);
            
            loadPanel(panelFrameCreate, constant.PANEL_FRAME, tglBtnCreate);
            
            frameString = constant.FRAME_EMP_CREATE;
        }
        
    }//GEN-LAST:event_tglBtnCreateActionPerformed

    private void menuItemEmpUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemEmpUpdateActionPerformed
        
        progressBar.setIndeterminate(true);
        progressBar.setString("Calling");
        
        loadPanel(new project_001_hris.PanelPopupUpdate(), constant.PANEL_POPUP, new JToggleButton());
        loadDialog("", 500, 248);
        
    }//GEN-LAST:event_menuItemEmpUpdateActionPerformed

    private void menuItemEmpDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemEmpDeleteActionPerformed

        progressBar.setIndeterminate(true);
        progressBar.setString("Calling");

        loadPanel(new project_001_hris.PanelPopupDelete(), constant.PANEL_POPUP, new JToggleButton());
        loadDialog("", 500, 248);

    }//GEN-LAST:event_menuItemEmpDeleteActionPerformed

    private void menuItemEmpDeleteManyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemEmpDeleteManyActionPerformed
        
        // TODO add your handling code here:
        
    }//GEN-LAST:event_menuItemEmpDeleteManyActionPerformed

    private void tglBtnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglBtnPrintActionPerformed
        
        
        
    }//GEN-LAST:event_tglBtnPrintActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

        JDialog dialog = new DialogSettings(this, true);
        loadPanel(new project_001_hris.PanelPopupDelete(), constant.PANEL_POPUP, new JToggleButton());
        dialog.setModal(true);
        dialog.setVisible(true);

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void menuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemExitActionPerformed

        int exitOption = JOptionPane.showConfirmDialog(FrameMain.this, "Are you sure you want to exit the program?", "", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        
        switch (exitOption) {
            case JOptionPane.YES_OPTION:
                System.exit(0);
                break;

            case JOptionPane.NO_OPTION:
                break;
        }

    }//GEN-LAST:event_menuItemExitActionPerformed

    private void menuItemLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemLogOutActionPerformed

        FrameLogin frm = new FrameLogin();
        
        try {  // Open program if successful.
            frm.pack();
            frm.setVisible(true);
            this.dispose();
        } catch (Exception e) {  // Close program if error.
            frm.dispose();
            JOptionPane.showMessageDialog(this, e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_menuItemLogOutActionPerformed

    private void tglBtnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglBtnHomeActionPerformed
        
        if(!frameString.equals(constant.FRAME_HOME)) {
            
            getMainLayout().show(panelCenter, "Card Center Open");
            panelMain.removeAll();
            
            frameString = constant.FRAME_HOME;
        }
        
    }//GEN-LAST:event_tglBtnHomeActionPerformed

    public void setButtons(Boolean bool, JToggleButton tButton, Boolean bool2) {

        tglBtnSearch.setEnabled(bool);
        tglBtnCreate.setEnabled(bool);
        tglBtnUpdate.setEnabled(bool);
        tglBtnDelete.setEnabled(bool);
        tglBtnPrint.setEnabled(bool);
        
        if (bool == true) {
            tglBtnSearch.setForeground(new Color(25, 25, 25));
            tglBtnCreate.setForeground(new Color(25, 25, 25));
            tglBtnUpdate.setForeground(new Color(25, 25, 25));
            tglBtnDelete.setForeground(new Color(25, 25, 25));
            tglBtnPrint.setForeground(new Color(25, 25, 25));
        } else {
            tglBtnSearch.setForeground(new Color(125, 125, 125));
            tglBtnCreate.setForeground(new Color(125, 125, 125));
            tglBtnUpdate.setForeground(new Color(125, 125, 125));
            tglBtnDelete.setForeground(new Color(125, 125, 125));
            tglBtnPrint.setForeground(new Color(125, 125, 125));
        }
        
        if (bool2 == true) {
            tButton.setSelected(true);
        } else {
            tButton.setSelected(false);
        }

    }

    public void loadDialog(String title, int width, int height) {

        dialogPopup.setTitle(title);
        dialogPopup.setSize(width, height);
        
        final Toolkit toolkit = Toolkit.getDefaultToolkit();
        final Dimension screenSize = toolkit.getScreenSize();
        final int x = (screenSize.width - dialogPopup.getWidth()) / 2;
        final int y = (screenSize.height - dialogPopup.getHeight()) / 2;
        dialogPopup.setLocation(x, y);
        
        dialogPopup.setVisible(true);

    }

    /**
     *
     * @param panel
     * @param type frame(1) or pop-up(2)
     * @param tButton
     */
    public void loadPanel(final JPanel panel, final int type, final JToggleButton tButton) {

        setButtons(false, tButton, true);

        @SuppressWarnings("unchecked")

        SwingWorker<Void, Void> sw = new SwingWorker() {

            @Override
            protected Object doInBackground() throws Exception {

                getMainLayout().show(panelCenter, "Card Center Load");
                progressBar.setString("Loading");
                progressBar.setValue(0);
                progressBar.setVisible(true);
                progressBar.setIndeterminate(true);

                try {
                    if (type == constant.PANEL_FRAME) {
                        if (panelFrame == null || panelFrame.isVisible()) {

                            panelMain.removeAll();
                            panelFrame = panel;
                            panelMain.add(panelFrame);

                        }
                    } else if (type == constant.PANEL_POPUP) {
                        if (panelPopup == null || panelPopup.isVisible()) {

                            dialogPopupPanelC.removeAll();
                            panelPopup = panel;
                            dialogPopupPanelC.add(panelPopup);

                        }
                    }

                    progressBar.setString("Preparing");

                } catch (Exception ex) {
                    progressBar.setString("Failed");
                    System.out.println(ex.getMessage());
                    JOptionPane.showMessageDialog(null, "Error Occured When Loading", "ERROR!", JOptionPane.ERROR_MESSAGE);
                }
                progressBar.setString("Initializing");
                return null;
            }

            @Override
            protected void done() {
                new java.util.Timer().schedule(
                        new java.util.TimerTask() {
                            @Override
                            public void run() {

                                progressBar.setString("Complete");
                                progressBar.setVisible(true);
                                progressBar.setValue(100);
                                progressBar.setIndeterminate(false);

                                getMainLayout().show(panelCenter, "Card Center Main");

                                setButtons(true, tButton, true);

                            }
                        },
                        1000
                );
            }
        };

        sw.execute();

    }

    private CardLayout getMainLayout() {

        CardLayout mainLayout = (CardLayout) panelCenter.getLayout();
        return mainLayout;

    }

    private void closeProgram() {

        addWindowListener(new WindowAdapter() {

            @Override
            public void windowClosing(WindowEvent e) {
                int exitOption = JOptionPane.showConfirmDialog(FrameMain.this, "Are you sure you want to exit the program?", "", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);

                if (exitOption == JOptionPane.YES_OPTION) {
                    System.exit(0);
                } else {
                    setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
                }
            }

        });

    }

    public JProgressBar getProgressBar() {
        return progressBar;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new FrameMain().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btngrpToolBar;
    private javax.swing.JDialog dialogPopup;
    private javax.swing.JPanel dialogPopupPanelC;
    private javax.swing.JPanel dialogPopupPanelL;
    private javax.swing.JPanel dialogPopupPanelR;
    private javax.swing.JPanel dialogPopupPanelT;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JToolBar.Separator jSeparator;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JLabel lblAboutLogo;
    private javax.swing.JLabel lblCenterLoad;
    private javax.swing.JLabel lblCenterOpen;
    private javax.swing.JLabel lblLoadingText;
    private javax.swing.JSeparator mainSeparator;
    private javax.swing.JMenu menuAccount;
    private javax.swing.JPopupMenu.Separator menuAccountSeparator;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JCheckBoxMenuItem menuCheckBoxMax;
    private javax.swing.JMenu menuFile;
    private javax.swing.JPopupMenu.Separator menuFileSeparator;
    private javax.swing.JMenu menuHelp;
    private javax.swing.JPopupMenu.Separator menuHelpSeparator;
    private javax.swing.JMenuItem menuItemAbout;
    private javax.swing.JMenuItem menuItemAccountCreate;
    private javax.swing.JMenuItem menuItemAccountManage;
    private javax.swing.JMenuItem menuItemAccountManageAll;
    private javax.swing.JMenuItem menuItemEmpCreate;
    private javax.swing.JMenuItem menuItemEmpDelete;
    private javax.swing.JMenuItem menuItemEmpDeleteMany;
    private javax.swing.JMenuItem menuItemEmpSearch;
    private javax.swing.JMenuItem menuItemEmpUpdate;
    private javax.swing.JMenuItem menuItemExit;
    private javax.swing.JMenuItem menuItemLogOut;
    private javax.swing.JMenuItem menuItemRecycle;
    private javax.swing.JMenuItem menuItemReport;
    private javax.swing.JMenuItem menuItemStart;
    private javax.swing.JMenuItem menuItemThemeColor;
    private javax.swing.JMenu menuTask;
    private javax.swing.JPopupMenu.Separator menuTaskSeparator;
    private javax.swing.JMenu menuTools;
    private javax.swing.JPopupMenu.Separator menuToolsSeparator;
    private javax.swing.JPanel panelCenter;
    private javax.swing.JPanel panelCenterLoad;
    private javax.swing.JPanel panelCenterMain;
    private javax.swing.JPanel panelCenterOpen;
    private javax.swing.JPanel panelMain;
    private javax.swing.JPanel panelMainBottom;
    private javax.swing.JPanel panelMainProgress;
    private javax.swing.JPanel panelToolbar;
    public javax.swing.JProgressBar progressBar;
    private javax.swing.JToggleButton tglBtnCreate;
    private javax.swing.JToggleButton tglBtnDelete;
    private javax.swing.JToggleButton tglBtnHome;
    private javax.swing.JToggleButton tglBtnPrint;
    private javax.swing.JToggleButton tglBtnSearch;
    private javax.swing.JToggleButton tglBtnUpdate;
    private javax.swing.JToolBar toolBar;
    private javax.swing.JLabel toolBarLabel;
    // End of variables declaration//GEN-END:variables

    private JPanel panelFrame;
    private JPanel panelPopup;

}
