/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package project_001_hris;

import java.awt.Font;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Blacqueous
 */
public final class PanelFrameSearch extends javax.swing.JPanel {
    
    Boolean form = true;
    ClassSearchBy searchBy = new ClassSearchBy();
    ClassFormatDateValue fmtDateVal = new ClassFormatDateValue();
    ClassConstantVariables constant = new ClassConstantVariables();
    final static ClassSliderJPanel slider = new ClassSliderJPanel();
    
    DefaultTableModel dtm;
    TableRowSorter<TableModel> sorter;
    
    ImageIcon imgBtnUpdate = new javax.swing.ImageIcon(getClass().getResource("/img_src/icon_16_track_changes_edit.png"));
    ImageIcon imgBtnDelete = new javax.swing.ImageIcon(getClass().getResource("/img_src/icon_16_bin.png"));
    ImageIcon imgBtnPrint = new javax.swing.ImageIcon(getClass().getResource("/img_src/icon_16_printer.png"));
    
    ClassJTableButtonEditor buttonUpdateEditor = new ClassJTableButtonEditor(new JCheckBox(), imgBtnUpdate);
    ClassJTableButtonRenderer buttonUpdateRender = new ClassJTableButtonRenderer(imgBtnUpdate);
    ClassJTableButtonEditor buttonDeleteEditor = new ClassJTableButtonEditor(new JCheckBox(), imgBtnDelete);
    ClassJTableButtonRenderer buttonDeleteRender = new ClassJTableButtonRenderer(imgBtnDelete);
    ClassJTableButtonEditor buttonPrintEditor = new ClassJTableButtonEditor(new JCheckBox(), imgBtnPrint);
    ClassJTableButtonRenderer buttonPrintRender = new ClassJTableButtonRenderer(imgBtnPrint);
    
    /**
     * Creates new form Panel_search
     */
    public PanelFrameSearch() {
        initComponents();
        initTable();
        panelSlide.add(initSlider());
//        loadTable("", "");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelTitle = new javax.swing.JPanel();
        labelAddNameFull7 = new javax.swing.JLabel();
        labelAddNameFull8 = new javax.swing.JLabel();
        panelSearchDetails = new javax.swing.JPanel();
        btnLessInfo = new javax.swing.JToggleButton();
        toggleButonView = new javax.swing.ButtonGroup();
        panelSearch = new javax.swing.JPanel();
        panelSearchSelect = new javax.swing.JPanel();
        panelSeparator = new javax.swing.JPanel();
        panelMainFormLeft = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        panelMainFormLeft1 = new javax.swing.JLabel();
        panelMainFormSeparator1 = new javax.swing.JSeparator();
        panelMainFormLeft2 = new javax.swing.JLabel();
        panelSlide = new javax.swing.JPanel();
        panelSearchMain = new javax.swing.JPanel();
        panelSearchFields = new javax.swing.JPanel();
        panelSearchField = new javax.swing.JPanel();
        lblSearch = new javax.swing.JLabel();
        cmbboxSearch = new santhosh.WideComboBox();
        panelSearchWithIcon = new javax.swing.JPanel();
        labelContactTele = new javax.swing.JLabel();
        txtfldSearch = new javax.swing.JTextField();
        panelTable = new javax.swing.JPanel();
        scrolpane = new javax.swing.JScrollPane();
        table_view = new javax.swing.JTable();
        panelTotal = new javax.swing.JPanel();
        labelSearchCountLabel = new javax.swing.JLabel();
        labelSearchCount = new javax.swing.JLabel();
        panelView = new javax.swing.JPanel();
        jPanel51 = new javax.swing.JPanel();
        jDesktopPane3 = new javax.swing.JDesktopPane();
        lblImage = new javax.swing.JLabel();
        labelAddGender10 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        panelAddLeft_Panel03 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        panelLessInfo = new javax.swing.JPanel();
        lblLessInfo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        btnMoreInfo = new javax.swing.JToggleButton();
        panelButtonLogo = new javax.swing.JPanel();
        labelLogo = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel5 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();

        panelTitle.setPreferredSize(new java.awt.Dimension(669, 25));
        panelTitle.setLayout(new java.awt.BorderLayout());

        labelAddNameFull7.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        labelAddNameFull7.setForeground(new java.awt.Color(0, 102, 102));
        labelAddNameFull7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelAddNameFull7.setToolTipText("");
        labelAddNameFull7.setPreferredSize(new java.awt.Dimension(25, 125));
        panelTitle.add(labelAddNameFull7, java.awt.BorderLayout.LINE_START);

        labelAddNameFull8.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        labelAddNameFull8.setText("SEARCH EMPLOYEE DATA");
        labelAddNameFull8.setPreferredSize(new java.awt.Dimension(125, 125));
        panelTitle.add(labelAddNameFull8, java.awt.BorderLayout.CENTER);

        toggleButonView.add(btnLessInfo);
        btnLessInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_src/icon_32_bullet_arrow_left.png"))); // NOI18N
        btnLessInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLessInfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelSearchDetailsLayout = new javax.swing.GroupLayout(panelSearchDetails);
        panelSearchDetails.setLayout(panelSearchDetailsLayout);
        panelSearchDetailsLayout.setHorizontalGroup(
            panelSearchDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSearchDetailsLayout.createSequentialGroup()
                .addContainerGap(404, Short.MAX_VALUE)
                .addComponent(btnLessInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelSearchDetailsLayout.setVerticalGroup(
            panelSearchDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSearchDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnLessInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
                .addContainerGap())
        );

        setPreferredSize(new java.awt.Dimension(874, 534));
        setLayout(new java.awt.BorderLayout());

        panelSearch.setLayout(new java.awt.BorderLayout());

        panelSearchSelect.setLayout(new java.awt.BorderLayout());

        panelSeparator.setPreferredSize(new java.awt.Dimension(10, 0));
        panelSeparator.setLayout(new java.awt.BorderLayout());

        panelMainFormLeft.setPreferredSize(new java.awt.Dimension(10, 10));
        panelSeparator.add(panelMainFormLeft, java.awt.BorderLayout.PAGE_START);

        jPanel12.setPreferredSize(new java.awt.Dimension(10, 0));
        jPanel12.setLayout(new java.awt.GridLayout(1, 0));

        panelMainFormLeft1.setPreferredSize(new java.awt.Dimension(10, 0));
        jPanel12.add(panelMainFormLeft1);

        panelMainFormSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel12.add(panelMainFormSeparator1);

        panelSeparator.add(jPanel12, java.awt.BorderLayout.CENTER);

        panelMainFormLeft2.setPreferredSize(new java.awt.Dimension(10, 10));
        panelSeparator.add(panelMainFormLeft2, java.awt.BorderLayout.PAGE_END);

        panelSearchSelect.add(panelSeparator, java.awt.BorderLayout.LINE_START);

        panelSlide.setLayout(new java.awt.CardLayout());

        panelSearchMain.setLayout(new java.awt.BorderLayout());

        panelSearchFields.setPreferredSize(new java.awt.Dimension(669, 50));
        panelSearchFields.setLayout(new java.awt.CardLayout(75, 9));

        panelSearchField.setPreferredSize(new java.awt.Dimension(550, 45));
        panelSearchField.setLayout(new java.awt.BorderLayout());

        lblSearch.setFont(new java.awt.Font("Century Gothic", 3, 12)); // NOI18N
        lblSearch.setForeground(new java.awt.Color(30, 30, 30));
        lblSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_src/icon_16_bullet_arrow_right.png"))); // NOI18N
        lblSearch.setText("Search :    ");
        panelSearchField.add(lblSearch, java.awt.BorderLayout.LINE_START);

        cmbboxSearch.setForeground(new java.awt.Color(51, 51, 51));
        cmbboxSearch.setFont(new java.awt.Font("Arial", 3, 11)); // NOI18N
        cmbboxSearch.setPreferredSize(new java.awt.Dimension(125, 15));
        cmbboxSearch.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbboxSearchItemStateChanged(evt);
            }
        });
        panelSearchField.add(cmbboxSearch, java.awt.BorderLayout.LINE_END);

        panelSearchWithIcon.setLayout(new java.awt.GridBagLayout());

        labelContactTele.setFont(new java.awt.Font("Century Gothic", 3, 14)); // NOI18N
        labelContactTele.setForeground(new java.awt.Color(50, 50, 50));
        labelContactTele.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_src/icon_16_magnifier.png"))); // NOI18N
        labelContactTele.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 0, 10);
        panelSearchWithIcon.add(labelContactTele, gridBagConstraints);

        txtfldSearch.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txtfldSearch.setForeground(new java.awt.Color(51, 51, 51));
        txtfldSearch.setMargin(new java.awt.Insets(2, 5, 2, 25));
        txtfldSearch.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtfldSearchCaretUpdate(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        panelSearchWithIcon.add(txtfldSearch, gridBagConstraints);

        panelSearchField.add(panelSearchWithIcon, java.awt.BorderLayout.CENTER);

        panelSearchFields.add(panelSearchField, "card2");

        panelSearchMain.add(panelSearchFields, java.awt.BorderLayout.PAGE_START);

        panelTable.setLayout(new java.awt.BorderLayout());

        table_view.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        table_view.setRowHeight(30);
        scrolpane.setViewportView(table_view);

        panelTable.add(scrolpane, java.awt.BorderLayout.CENTER);

        panelTotal.setPreferredSize(new java.awt.Dimension(669, 40));
        panelTotal.setLayout(new java.awt.BorderLayout());

        labelSearchCountLabel.setFont(new java.awt.Font("Century Gothic", 3, 11)); // NOI18N
        labelSearchCountLabel.setForeground(new java.awt.Color(30, 30, 30));
        labelSearchCountLabel.setText("   SEARCH TOTAL  :  ");
        panelTotal.add(labelSearchCountLabel, java.awt.BorderLayout.LINE_START);

        labelSearchCount.setFont(new java.awt.Font("Century Gothic", 2, 10)); // NOI18N
        labelSearchCount.setForeground(new java.awt.Color(25, 25, 25));
        labelSearchCount.setText("0 result");
        panelTotal.add(labelSearchCount, java.awt.BorderLayout.CENTER);

        panelTable.add(panelTotal, java.awt.BorderLayout.PAGE_END);

        panelSearchMain.add(panelTable, java.awt.BorderLayout.CENTER);

        panelSlide.add(panelSearchMain, "card2");

        panelSearchSelect.add(panelSlide, java.awt.BorderLayout.CENTER);

        panelSearch.add(panelSearchSelect, java.awt.BorderLayout.CENTER);

        panelView.setPreferredSize(new java.awt.Dimension(175, 292));
        panelView.setLayout(new java.awt.BorderLayout());

        jPanel51.setPreferredSize(new java.awt.Dimension(300, 210));

        jDesktopPane3.setPreferredSize(new java.awt.Dimension(75, 75));

        lblImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jDesktopPane3Layout = new javax.swing.GroupLayout(jDesktopPane3);
        jDesktopPane3.setLayout(jDesktopPane3Layout);
        jDesktopPane3Layout.setHorizontalGroup(
            jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDesktopPane3Layout.setVerticalGroup(
            jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblImage, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
        );
        jDesktopPane3.setLayer(lblImage, javax.swing.JLayeredPane.DEFAULT_LAYER);

        labelAddGender10.setBackground(new java.awt.Color(242, 242, 242));
        labelAddGender10.setFont(new java.awt.Font("Century Gothic", 3, 11)); // NOI18N
        labelAddGender10.setForeground(new java.awt.Color(30, 30, 30));
        labelAddGender10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelAddGender10.setText("-");
        labelAddGender10.setOpaque(true);
        labelAddGender10.setPreferredSize(new java.awt.Dimension(80, 80));

        javax.swing.GroupLayout jPanel51Layout = new javax.swing.GroupLayout(jPanel51);
        jPanel51.setLayout(jPanel51Layout);
        jPanel51Layout.setHorizontalGroup(
            jPanel51Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel51Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel51Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDesktopPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                    .addComponent(labelAddGender10, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel51Layout.setVerticalGroup(
            jPanel51Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel51Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jDesktopPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelAddGender10, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelView.add(jPanel51, java.awt.BorderLayout.PAGE_START);

        jPanel15.setPreferredSize(new java.awt.Dimension(2, 25));
        jPanel15.setLayout(new java.awt.BorderLayout());
        panelView.add(jPanel15, java.awt.BorderLayout.LINE_START);

        jPanel17.setPreferredSize(new java.awt.Dimension(669, 25));
        jPanel17.setLayout(new java.awt.BorderLayout());

        panelAddLeft_Panel03.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        panelAddLeft_Panel03.setPreferredSize(new java.awt.Dimension(669, 25));
        panelAddLeft_Panel03.setLayout(new java.awt.CardLayout(23, 0));

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel3.setLayout(new java.awt.BorderLayout());

        panelLessInfo.setPreferredSize(new java.awt.Dimension(105, 105));
        panelLessInfo.setLayout(new java.awt.BorderLayout());

        lblLessInfo.setFont(new java.awt.Font("Arial", 3, 11)); // NOI18N
        lblLessInfo.setForeground(new java.awt.Color(30, 30, 30));
        lblLessInfo.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblLessInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_src/icon_16_question2.png"))); // NOI18N
        lblLessInfo.setText("More info?          ");
        lblLessInfo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblLessInfo.setIconTextGap(5);
        lblLessInfo.setPreferredSize(new java.awt.Dimension(0, 30));
        panelLessInfo.add(lblLessInfo, java.awt.BorderLayout.PAGE_END);
        lblLessInfo.getAccessibleContext().setAccessibleName("More info?");

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setText("<html><b>Mr. _______</b> has been an employee since <b>January 1, 1070</b>.</html>");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        panelLessInfo.add(jLabel1, java.awt.BorderLayout.CENTER);

        jPanel3.add(panelLessInfo, java.awt.BorderLayout.PAGE_START);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel2.setPreferredSize(new java.awt.Dimension(5, 5));
        jPanel1.add(jLabel2, java.awt.BorderLayout.PAGE_START);

        jPanel7.setLayout(new java.awt.BorderLayout());

        toggleButonView.add(btnMoreInfo);
        btnMoreInfo.setFont(new java.awt.Font("Century Gothic", 1, 13)); // NOI18N
        btnMoreInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_src/icon_32_info_card.png"))); // NOI18N
        btnMoreInfo.setText("Click here");
        btnMoreInfo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMoreInfo.setPreferredSize(new java.awt.Dimension(105, 105));
        btnMoreInfo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnMoreInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoreInfoActionPerformed(evt);
            }
        });
        jPanel7.add(btnMoreInfo, java.awt.BorderLayout.PAGE_START);

        panelButtonLogo.setLayout(new java.awt.CardLayout(15, 10));

        labelLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_src/icon_16_logo_hris_img.png"))); // NOI18N
        labelLogo.setEnabled(false);
        labelLogo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelButtonLogo.add(labelLogo, "card3");

        jPanel7.add(panelButtonLogo, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel7, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel4.setPreferredSize(new java.awt.Dimension(100, 48));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel6.setPreferredSize(new java.awt.Dimension(113, 4));
        jPanel6.setLayout(new java.awt.BorderLayout());
        jPanel6.add(jSeparator1, java.awt.BorderLayout.CENTER);

        jPanel5.setPreferredSize(new java.awt.Dimension(8, 8));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel5, java.awt.BorderLayout.LINE_START);

        jPanel10.setPreferredSize(new java.awt.Dimension(8, 8));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel10, java.awt.BorderLayout.LINE_END);

        jPanel4.add(jPanel6, java.awt.BorderLayout.PAGE_START);

        jPanel2.add(jPanel4, java.awt.BorderLayout.PAGE_END);

        jPanel9.setPreferredSize(new java.awt.Dimension(100, 8));
        jPanel9.setLayout(new java.awt.BorderLayout());
        jPanel2.add(jPanel9, java.awt.BorderLayout.PAGE_START);

        panelAddLeft_Panel03.add(jPanel2, "card3");

        jPanel17.add(panelAddLeft_Panel03, java.awt.BorderLayout.CENTER);

        panelView.add(jPanel17, java.awt.BorderLayout.CENTER);

        panelSearch.add(panelView, java.awt.BorderLayout.LINE_START);

        add(panelSearch, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void initTable() {
        
        // Set filter 
        comboBoxLoadFromConstants(constant.LIST_SEARCH_FILTER, cmbboxSearch, "Filter By:");
        
        // Set all needed variables by the table.
        buttonUpdateEditor.setTable(table_view);
        buttonDeleteEditor.setTable(table_view);
        buttonPrintEditor.setTable(table_view);
        buttonUpdateEditor.setPushAction("Search_Update");
        buttonDeleteEditor.setPushAction("Search_Delete");
        buttonPrintEditor.setPushAction("Search_Print");
        
        // Load DB data to table.
        initTableSearch(searchBy.searchBySelect(cmbboxSearch, txtfldSearch.getText().toUpperCase()));
        
    }
    

    /**
     * Initialize JPanel slider
     * 
     * @return ClassSliderJPanel
     */
    private static JComponent initSlider() {

        slider.addSliderComponent(panelSearchMain);
        slider.addSliderComponent(panelSearchDetails);
        slider.refresh();

        return slider;

    }

    private void txtfldSearchCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtfldSearchCaretUpdate
        
        initTableSearch(searchBy.searchBySelect(cmbboxSearch, txtfldSearch.getText().toUpperCase()));
        
    }//GEN-LAST:event_txtfldSearchCaretUpdate

    private void cmbboxSearchItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbboxSearchItemStateChanged
        
        initTableSearch(searchBy.searchBySelect(cmbboxSearch, txtfldSearch.getText().toUpperCase()));
        
    }//GEN-LAST:event_cmbboxSearchItemStateChanged

    private void btnMoreInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoreInfoActionPerformed
        
        if(form) {
            slider.prev();
            slider.refresh();

            form = false;
        }        
        
    }//GEN-LAST:event_btnMoreInfoActionPerformed

    private void btnLessInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLessInfoActionPerformed
        
        if(!form) {
            slider.next();
            slider.refresh();
            
            form = true;
        }
        
    }//GEN-LAST:event_btnLessInfoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnLessInfo;
    private javax.swing.JToggleButton btnMoreInfo;
    private santhosh.WideComboBox cmbboxSearch;
    private javax.swing.JDesktopPane jDesktopPane3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel51;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelAddGender10;
    private javax.swing.JLabel labelAddNameFull7;
    private javax.swing.JLabel labelAddNameFull8;
    private javax.swing.JLabel labelContactTele;
    private javax.swing.JLabel labelLogo;
    private javax.swing.JLabel labelSearchCount;
    private javax.swing.JLabel labelSearchCountLabel;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblLessInfo;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JPanel panelAddLeft_Panel03;
    private javax.swing.JPanel panelButtonLogo;
    private javax.swing.JPanel panelLessInfo;
    private javax.swing.JLabel panelMainFormLeft;
    private javax.swing.JLabel panelMainFormLeft1;
    private javax.swing.JLabel panelMainFormLeft2;
    private javax.swing.JSeparator panelMainFormSeparator1;
    private javax.swing.JPanel panelSearch;
    private static javax.swing.JPanel panelSearchDetails;
    private javax.swing.JPanel panelSearchField;
    private javax.swing.JPanel panelSearchFields;
    private static javax.swing.JPanel panelSearchMain;
    private javax.swing.JPanel panelSearchSelect;
    private javax.swing.JPanel panelSearchWithIcon;
    private javax.swing.JPanel panelSeparator;
    private javax.swing.JPanel panelSlide;
    private javax.swing.JPanel panelTable;
    private javax.swing.JPanel panelTitle;
    private javax.swing.JPanel panelTotal;
    private javax.swing.JPanel panelView;
    private javax.swing.JScrollPane scrolpane;
    private javax.swing.JTable table_view;
    private javax.swing.ButtonGroup toggleButonView;
    private javax.swing.JTextField txtfldSearch;
    // End of variables declaration//GEN-END:variables

    private void initTableSearch(String addWhere) {
        
        ArrayList<Object> columnTitle = new ArrayList<>();
        ArrayList<Object> addRow;
        int rowCount = 0;

        this.dtm = new DefaultTableModel(){
            @Override
            public Class getColumnClass(int column){
                Class returnValue;
                try {
                    if((column>=0) && (column<getColumnCount()) && (column!=2)) {
                        returnValue = getValueAt(0, column).getClass();
                    } else {
                        returnValue = Object.class;
                    }
                } catch (Exception ex) {
//                    System.out.println(ex.getMessage());
                    returnValue = Object.class;
                }
                return returnValue;
            }
            @Override
            public boolean isCellEditable(int row, int column) {
                switch(column) {
                    case 1:
                        return true;
                    case 2:
                        return true;
                    case 3:
                        return true;
                    default:
                        return false;
                }
            }
        };
        
        ClassMyDBConnectionEmbeddedDerby.initDB();
        
        try {
            Connection conn = ClassMyDBConnectionEmbeddedDerby.getMyConnection();
            try (Statement st = conn.createStatement()) {
                ResultSet rs = st.executeQuery(
                    "SELECT " 
                        + " h.id, " 
                        + " COALESCE(h.name_first || ' ', '') || COALESCE(h.name_middle || ' ', '') || h.name_last AS \"Employee Name\", " 
                        + " h.plantilla_id AS \"Plantilla No.\", " 
                        + " p.name AS \"Position\", " 
                        + " o.name AS \"Office\", " 
                        + " c.name AS \"Category\", " 
                        + " h.date_hired AS \"Date Hired\", " 
                        + " d.gender AS \"Gender\", " 
                        + " d.civil_status AS \"Civil Status\", " 
                        + " d.date_birth AS \"Date of Birth\" " 
                    + " FROM " 
                        + constant.TABLE_EMPLOYEE_HEADER + " AS h " 
                    + " LEFT JOIN " + constant.TABLE_EMPLOYEE_DETAIL + " AS d ON h.id=d.header_id " 
                    + " LEFT JOIN " + constant.TABLE_LIST_OFFICE     + " AS o ON h.list_off_id=o.id " 
                    + " LEFT JOIN " + constant.TABLE_LIST_POSITION   + " AS p ON h.list_pos_id=p.id " 
                    + " LEFT JOIN " + constant.TABLE_LIST_CATEGORY   + " AS c ON h.list_cat_id=c.id " 
                    + " WHERE " + addWhere
                );
                
                ResultSetMetaData rsm = rs.getMetaData();
                int columnCount = rsm.getColumnCount();
                
                for (int i = 1; i <= columnCount; i++) {
                    columnTitle.add(rsm.getColumnName(i));
                    if(i==1){
                        columnTitle.add("");
                        columnTitle.add("");
                        columnTitle.add("");
                    }
                }
                
                // Set Column Headers
                dtm.setDataVector(null, columnTitle.toArray());
                
                while (rs.next()) {
                    addRow = new ArrayList<>();
                    for (int i = 1; i <= columnCount; i++) {
                        if(i==7 || i==10){
                            addRow.add(fmtDateVal.formatDateToString(fmtDateVal.formatStringToDate(rs.getString(i)), "MMMM dd, YYYY"));
                        } else {
                            addRow.add(rs.getString(i));
                        }
                        
                        if(i==1){
                            addRow.add("");
                            addRow.add("");
                            addRow.add("");
                        }
                    }
                    dtm.addRow(addRow.toArray());
                
                    rowCount++;
                }
            
            }
        } catch(SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage() + "\nClosing system.", "Database Connection: Failed", JOptionPane.ERROR_MESSAGE);
            System.exit(0);
        }
        
        // Set created TableModel
        table_view.setModel(dtm);
        table_view.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        
        // Employee's ID
        table_view.getColumnModel().getColumn(0).setMinWidth(0);
        table_view.getColumnModel().getColumn(0).setPreferredWidth(0);
        table_view.getColumnModel().getColumn(0).setResizable(false);
        
        // Update row button
        table_view.getColumnModel().getColumn(1).setCellEditor(buttonUpdateEditor);
        table_view.getColumnModel().getColumn(1).setCellRenderer(buttonUpdateRender);
        table_view.getColumnModel().getColumn(1).setPreferredWidth(30);
        table_view.getColumnModel().getColumn(1).setResizable(false);
        
        // Delete row button
        table_view.getColumnModel().getColumn(2).setCellEditor(buttonDeleteEditor);
        table_view.getColumnModel().getColumn(2).setCellRenderer(buttonDeleteRender);
        table_view.getColumnModel().getColumn(2).setPreferredWidth(30);
        table_view.getColumnModel().getColumn(2).setResizable(false);
        
        // Print row button
        table_view.getColumnModel().getColumn(3).setCellEditor(buttonPrintEditor);
        table_view.getColumnModel().getColumn(3).setCellRenderer(buttonPrintRender);
        table_view.getColumnModel().getColumn(3).setPreferredWidth(30);
        table_view.getColumnModel().getColumn(3).setResizable(false);
        
        // Employee's name
        table_view.getColumnModel().getColumn(4).setMinWidth(385);
        table_view.getColumnModel().getColumn(4).setPreferredWidth(385);
        
        // Employee's plantilla number
        table_view.getColumnModel().getColumn(5).setMinWidth(113);
        table_view.getColumnModel().getColumn(5).setPreferredWidth(113);
        
        // Employee's position
        table_view.getColumnModel().getColumn(6).setMinWidth(155);
        table_view.getColumnModel().getColumn(6).setPreferredWidth(155);
        
        // Employee's office
        table_view.getColumnModel().getColumn(7).setMinWidth(230);
        table_view.getColumnModel().getColumn(7).setPreferredWidth(230);
        
        // Employee's category
        table_view.getColumnModel().getColumn(8).setMinWidth(152);
        table_view.getColumnModel().getColumn(8).setPreferredWidth(152);
        
        // Employee's date hired
        table_view.getColumnModel().getColumn(9).setMinWidth(140);
        table_view.getColumnModel().getColumn(9).setPreferredWidth(140);
        
        // Employee's gender
        table_view.getColumnModel().getColumn(10).setMinWidth(75);
        table_view.getColumnModel().getColumn(10).setPreferredWidth(75);
        
        // Employee's civil status
        table_view.getColumnModel().getColumn(11).setMinWidth(100);
        table_view.getColumnModel().getColumn(11).setPreferredWidth(100);
        
        // Employee's date of birth
        table_view.getColumnModel().getColumn(12).setMinWidth(140);
        table_view.getColumnModel().getColumn(12).setPreferredWidth(140);
        
        JTableHeader th = table_view.getTableHeader();
        th.setFont(new Font("Century Gothic", Font.BOLD, 13));
        
//        DefaultTableCellRenderer renderHeaderLeft = (DefaultTableCellRenderer)table_view.getTableHeader().getDefaultRenderer();
//        renderHeaderLeft.setHorizontalAlignment(JLabel.LEFT);
//        table_view.getColumnModel().getColumn(0).setHeaderRenderer(renderHeaderLeft);
        
//        DefaultTableCellRenderer renderHeaderRight = (DefaultTableCellRenderer)table_view.getTableHeader().getDefaultRenderer();
//        renderHeaderRight.setHorizontalAlignment(JLabel.RIGHT);
//        table_view.getColumnModel().getColumn(0).setHeaderRenderer(renderHeaderRight);
        
        DefaultTableCellRenderer renderHeaderCenter = (DefaultTableCellRenderer)table_view.getTableHeader().getDefaultRenderer();
        renderHeaderCenter.setHorizontalAlignment(SwingConstants.CENTER);
        table_view.getColumnModel().getColumn(0).setHeaderRenderer(renderHeaderCenter);
        
        DefaultTableCellRenderer renderCellLeft = new DefaultTableCellRenderer();
        renderCellLeft.setHorizontalAlignment(SwingConstants.LEFT);
        table_view.getColumnModel().getColumn(4).setCellRenderer(renderCellLeft);
        table_view.getColumnModel().getColumn(7).setCellRenderer(renderCellLeft);
        
        DefaultTableCellRenderer renderCellCenter = new DefaultTableCellRenderer();
        renderCellCenter.setHorizontalAlignment(SwingConstants.CENTER);
        table_view.getColumnModel().getColumn(5).setCellRenderer(renderCellCenter);
        table_view.getColumnModel().getColumn(6).setCellRenderer(renderCellCenter);
        table_view.getColumnModel().getColumn(8).setCellRenderer(renderCellCenter);
        table_view.getColumnModel().getColumn(9).setCellRenderer(renderCellCenter);
        table_view.getColumnModel().getColumn(10).setCellRenderer(renderCellCenter);
        table_view.getColumnModel().getColumn(11).setCellRenderer(renderCellCenter);
        table_view.getColumnModel().getColumn(12).setCellRenderer(renderCellCenter);
        
        sorter = new TableRowSorter<TableModel>(dtm);
        table_view.setRowSorter(sorter);
        
        table_view.repaint();
        
        labelSearchCount.setText( rowCount + ((rowCount <= 1) ? " result" : " results"));
        
    }

    private void comboBoxLoadFromConstants(ArrayList array, JComboBox cmbbox, String title) {
        
        DefaultComboBoxModel dcbm = new DefaultComboBoxModel();
        dcbm.addElement("");
        
        for (int i = 0; i < array.size(); i++) {
            dcbm.addElement(array.get(i));
        }
        
        cmbbox.setModel(dcbm);
        ClassComplexCellRenderer renderer = new ClassComplexCellRenderer();
        renderer.title = title;
        cmbbox.setRenderer(renderer);
        
    }

}
