/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project_001_hris;

import java.awt.CardLayout;
import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.image.BufferedImage;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JToggleButton;
import javax.swing.SwingWorker;

/**
 *
 * @author Blacqueous
 */
public class PanelFrameCreate extends javax.swing.JPanel {

    Boolean form = true;
    JFrame frame = new JFrame();
    Calendar currentDate = Calendar.getInstance();
    ClassGetComboBoxValue cmbboxId = new ClassGetComboBoxValue();
    ClassConstantVariables constant = new ClassConstantVariables();
    ClassCapitalize capital = new ClassCapitalize();
    DefaultListModel dModel = new DefaultListModel();
    DefaultListModel tModel = new DefaultListModel();
    DefaultListModel eModel = new DefaultListModel();
    PanelFrameCreateViewByList createFormList = new PanelFrameCreateViewByList();
    PanelFrameCreateViewByGrid createFormGrid = new PanelFrameCreateViewByGrid();
    JTable[] field = new JTable[3];
    BufferedImage image;

    /**
     * Creates new form PanelCreate
     */
    public PanelFrameCreate() {
        initComponents();
        initAdditionalComponents();
//        ClassMyDBConnectionEmbeddedDerby.initDB();
        getMainLayout().show(panelMainFormCenter, "Card Load");
        btnFormOptionsList.setSelected(true);
        createFormList.setFrame(frame);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createFormSwitch = new javax.swing.ButtonGroup();
        panelNew = new javax.swing.JPanel();
        panelMain = new javax.swing.JPanel();
        panelMainFormCenter = new javax.swing.JPanel();
        panelMainForm = new javax.swing.JPanel();
        panelMainFormLoad = new javax.swing.JPanel();
        lblCenterLoad = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        panelMainFormLeft = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        panelMainFormLeft1 = new javax.swing.JLabel();
        panelMainFormSeparator1 = new javax.swing.JSeparator();
        panelMainFormLeft2 = new javax.swing.JLabel();
        panelAddLeft = new javax.swing.JPanel();
        panelAddLeft_Panel01 = new javax.swing.JPanel();
        jDesktopPane3 = new javax.swing.JDesktopPane();
        lblImage = new javax.swing.JLabel();
        btnUpload = new javax.swing.JButton();
        txtfldImg = new javax.swing.JTextField();
        panelAddLeft_Panel02 = new javax.swing.JPanel();
        panelAddLeft_Panel03 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnSave = new javax.swing.JButton();
        panelButtons = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnClear = new javax.swing.JButton();
        panelButtonLogo = new javax.swing.JPanel();
        labelLogo = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        btFormSwitch = new javax.swing.JPanel();
        btnFormOptionsGrid = new javax.swing.JToggleButton();
        btnFormOptionsList = new javax.swing.JToggleButton();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        panelNew.setLayout(new java.awt.BorderLayout());

        panelMain.setLayout(new java.awt.BorderLayout());

        panelMainFormCenter.setLayout(new java.awt.CardLayout());

        panelMainForm.setLayout(new java.awt.CardLayout());
        panelMainFormCenter.add(panelMainForm, "Card Form");

        panelMainFormLoad.setLayout(new java.awt.GridBagLayout());

        lblCenterLoad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_src/loading.gif"))); // NOI18N
        panelMainFormLoad.add(lblCenterLoad, new java.awt.GridBagConstraints());

        panelMainFormCenter.add(panelMainFormLoad, "Card Load");

        panelMain.add(panelMainFormCenter, java.awt.BorderLayout.CENTER);

        jPanel8.setPreferredSize(new java.awt.Dimension(10, 0));
        jPanel8.setLayout(new java.awt.BorderLayout());

        panelMainFormLeft.setPreferredSize(new java.awt.Dimension(10, 10));
        jPanel8.add(panelMainFormLeft, java.awt.BorderLayout.PAGE_START);

        jPanel9.setPreferredSize(new java.awt.Dimension(10, 0));
        jPanel9.setLayout(new java.awt.GridLayout(1, 0));

        panelMainFormLeft1.setPreferredSize(new java.awt.Dimension(10, 0));
        jPanel9.add(panelMainFormLeft1);

        panelMainFormSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel9.add(panelMainFormSeparator1);

        jPanel8.add(jPanel9, java.awt.BorderLayout.CENTER);

        panelMainFormLeft2.setPreferredSize(new java.awt.Dimension(10, 10));
        jPanel8.add(panelMainFormLeft2, java.awt.BorderLayout.PAGE_END);

        panelMain.add(jPanel8, java.awt.BorderLayout.LINE_START);

        panelNew.add(panelMain, java.awt.BorderLayout.CENTER);

        panelAddLeft.setPreferredSize(new java.awt.Dimension(175, 292));
        panelAddLeft.setLayout(new java.awt.BorderLayout());

        panelAddLeft_Panel01.setPreferredSize(new java.awt.Dimension(300, 210));

        jDesktopPane3.setPreferredSize(new java.awt.Dimension(75, 75));

        lblImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jDesktopPane3Layout = new javax.swing.GroupLayout(jDesktopPane3);
        jDesktopPane3.setLayout(jDesktopPane3Layout);
        jDesktopPane3Layout.setHorizontalGroup(
            jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDesktopPane3Layout.setVerticalGroup(
            jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblImage, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
        );
        jDesktopPane3.setLayer(lblImage, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btnUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadActionPerformed(evt);
            }
        });

        txtfldImg.setEditable(false);
        txtfldImg.setEnabled(false);

        javax.swing.GroupLayout panelAddLeft_Panel01Layout = new javax.swing.GroupLayout(panelAddLeft_Panel01);
        panelAddLeft_Panel01.setLayout(panelAddLeft_Panel01Layout);
        panelAddLeft_Panel01Layout.setHorizontalGroup(
            panelAddLeft_Panel01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAddLeft_Panel01Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(panelAddLeft_Panel01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDesktopPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                    .addGroup(panelAddLeft_Panel01Layout.createSequentialGroup()
                        .addComponent(txtfldImg, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpload, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelAddLeft_Panel01Layout.setVerticalGroup(
            panelAddLeft_Panel01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAddLeft_Panel01Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jDesktopPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(panelAddLeft_Panel01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnUpload, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(txtfldImg))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelAddLeft.add(panelAddLeft_Panel01, java.awt.BorderLayout.PAGE_START);

        panelAddLeft_Panel02.setPreferredSize(new java.awt.Dimension(2, 25));
        panelAddLeft_Panel02.setLayout(new java.awt.BorderLayout());
        panelAddLeft.add(panelAddLeft_Panel02, java.awt.BorderLayout.LINE_START);

        panelAddLeft_Panel03.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        panelAddLeft_Panel03.setPreferredSize(new java.awt.Dimension(669, 25));
        panelAddLeft_Panel03.setLayout(new java.awt.CardLayout(23, 8));

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel3.setLayout(new java.awt.BorderLayout());

        btnSave.setFont(new java.awt.Font("Century Gothic", 1, 13)); // NOI18N
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_src/icon_32_plus_color.png"))); // NOI18N
        btnSave.setText("SAVE");
        btnSave.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSave.setPreferredSize(new java.awt.Dimension(105, 105));
        btnSave.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel3.add(btnSave, java.awt.BorderLayout.PAGE_START);

        panelButtons.setLayout(new java.awt.BorderLayout());

        jLabel1.setPreferredSize(new java.awt.Dimension(5, 5));
        panelButtons.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanel1.setLayout(new java.awt.BorderLayout());

        btnClear.setFont(new java.awt.Font("Century Gothic", 1, 13)); // NOI18N
        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_src/icon_32_draw_eraser_color.png"))); // NOI18N
        btnClear.setText("CLEAR");
        btnClear.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnClear.setPreferredSize(new java.awt.Dimension(105, 105));
        btnClear.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel1.add(btnClear, java.awt.BorderLayout.PAGE_START);

        panelButtonLogo.setLayout(new java.awt.CardLayout(15, 10));

        labelLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_src/icon_16_logo_hris_img.png"))); // NOI18N
        labelLogo.setEnabled(false);
        labelLogo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelButtonLogo.add(labelLogo, "card3");

        jPanel1.add(panelButtonLogo, java.awt.BorderLayout.CENTER);

        panelButtons.add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel3.add(panelButtons, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel4.setPreferredSize(new java.awt.Dimension(100, 40));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel6.setPreferredSize(new java.awt.Dimension(113, 4));
        jPanel6.setLayout(new java.awt.BorderLayout());
        jPanel6.add(jSeparator1, java.awt.BorderLayout.CENTER);

        jPanel5.setPreferredSize(new java.awt.Dimension(8, 8));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel5, java.awt.BorderLayout.LINE_START);

        jPanel7.setPreferredSize(new java.awt.Dimension(8, 8));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel7, java.awt.BorderLayout.LINE_END);

        jPanel4.add(jPanel6, java.awt.BorderLayout.PAGE_START);

        btFormSwitch.setLayout(new java.awt.GridLayout(1, 0));

        btnFormOptionsGrid.setBackground(new java.awt.Color(230, 230, 230));
        createFormSwitch.add(btnFormOptionsGrid);
        btnFormOptionsGrid.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_src/icon_16_view_icons.png"))); // NOI18N
        btnFormOptionsGrid.setPreferredSize(new java.awt.Dimension(40, 40));
        btnFormOptionsGrid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnFormOptionsGridMouseReleased(evt);
            }
        });
        btFormSwitch.add(btnFormOptionsGrid);

        btnFormOptionsList.setBackground(new java.awt.Color(230, 230, 230));
        createFormSwitch.add(btnFormOptionsList);
        btnFormOptionsList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_src/icon_16_view_scroll_pane_list.png"))); // NOI18N
        btnFormOptionsList.setPreferredSize(new java.awt.Dimension(40, 40));
        btnFormOptionsList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFormOptionsListActionPerformed(evt);
            }
        });
        btFormSwitch.add(btnFormOptionsList);

        jPanel4.add(btFormSwitch, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel10, java.awt.BorderLayout.LINE_START);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel11, java.awt.BorderLayout.LINE_END);

        jPanel2.add(jPanel4, java.awt.BorderLayout.PAGE_END);

        panelAddLeft_Panel03.add(jPanel2, "card3");

        panelAddLeft.add(panelAddLeft_Panel03, java.awt.BorderLayout.CENTER);

        panelNew.add(panelAddLeft, java.awt.BorderLayout.LINE_START);

        add(panelNew, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void initAdditionalComponents() {
        
        // Set starting form view
        loadPanel(createFormGrid, constant.PANEL_FRAME, btnFormOptionsGrid);
        form = false;
        
    }

    private void btnUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadActionPerformed

//        JFileChooser chooser = new JFileChooser();
//        FileNameExtensionFilter filter = new FileNameExtensionFilter(
//                "JPG, GIF, and PNG Images", "jpg", "gif", "png");
//        chooser.setFileFilter(filter);
//        int returnVal = chooser.showOpenDialog(frame);
//        if(returnVal == JFileChooser.APPROVE_OPTION) {
//            File file = chooser.getSelectedFile();
//            System.out.println("You chose to open this file: " + file.getName());
//            
//
//            String img_path = getClass().getResource("/img_emp_src/").getFile();
//            File img_path_file = new File(img_path);
//
//            try {
//                image = ImageIO.read(file);
//                ImageIO.write(image, "jpg", new File(img_path_file.getAbsolutePath() + "\\" + file.getName()));
//                System.out.println("Saving done...");
//            } catch (IOException ex) {
//                Logger.getLogger(SaveImageFile.class.getName()).log(Level.SEVERE, null, ex);
//            }
//        }
        
//        JFileChooser chooser = new JFileChooser();
//        chooser.showOpenDialog(null);
//        File f = chooser.getSelectedFile();
//        filename = f.getAbsolutePath();
//
//        txtfldImg.setText(filename);
//
//        try {
//
//            File image = new File(filename);
//            FileInputStream fis = new FileInputStream(image);
//
//            ByteArrayOutputStream baos = new ByteArrayOutputStream();
//            byte[] buff = new byte[1024];
//
//            for (int readNum; (readNum = fis.read(buff)) != -1;) {
//                baos.write(buff, 0, readNum);
//            }
//
//            emp_image = baos.toByteArray();
//            System.out.println(emp_image);
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(null, e);
//        }

    }//GEN-LAST:event_btnUploadActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        
        createFormGrid.clearFields();
        createFormList.clearFields();
        
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnFormOptionsGridMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFormOptionsGridMouseReleased
        
        if(form) {
            loadPanel(createFormGrid, constant.PANEL_FRAME, btnFormOptionsGrid);
            
            // Set data from the other form to fields. If exists.
            createFormGrid.setFieldsForSwitch(createFormList.getFieldsForSwitch());
            
            // Set fields color to normal.
            createFormGrid.resetFormFieldsColor();
            
            // Set data from the other form to tables. If exists.
            field = createFormList.getFormTables();
            createFormGrid.setFormTables(field);
            
            form = false;
        }
        
    }//GEN-LAST:event_btnFormOptionsGridMouseReleased

    private void btnFormOptionsListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFormOptionsListActionPerformed
        
        if(!form) {
            loadPanel(createFormList, constant.PANEL_FRAME, btnFormOptionsList);
            
            // Set data from the other form to fields. If exists.
            createFormList.setFieldsForSwitch(createFormGrid.getFieldsForSwitch());
            
            // Set fields color to normal.
            createFormList.resetFormFieldsColor();
            
            // Set data from the other form to tables. If exists.
            field = createFormGrid.getFormTables();
            createFormList.setFormTables(field);
            
            form = true;
        }
        
    }//GEN-LAST:event_btnFormOptionsListActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

        String[] formArray;

        if(createFormSwitch.isSelected(btnFormOptionsGrid.getModel())){
            formArray = createFormGrid.getFieldsForSave();
        } else {
            formArray = createFormList.getFieldsForSave();
        }

        if(formArray != null && formArray.length == 25) {

            int x = JOptionPane.showConfirmDialog(this, "Are you sure you want to Create New Employee Data?", "VALIDATE ACTION", JOptionPane.YES_NO_OPTION);

            if (x == 0) {

                try {
                    //Database connection
                    ClassMyDBConnectionEmbeddedDerby.initDB();
                    Connection conn = ClassMyDBConnectionEmbeddedDerby.getMyConnection();

                    PreparedStatement ps;

                    ps = conn.prepareStatement("INSERT INTO " + constant.TABLE_EMPLOYEE_HEADER + " (name_first, name_middle, name_last, plantilla_id, list_pos_id, list_off_id, list_cat_id, date_hired, salary) values ((?),(?),(?),(?),(?),(?),(?),(?),(?))", Statement.RETURN_GENERATED_KEYS);
                    ps.setString(1, formArray[0]); // name_first
                    ps.setString(2, formArray[1]); // name_middle
                    ps.setString(3, formArray[2]); // name_last
                    ps.setInt(4, Integer.parseInt(formArray[3])); // plantilla_id
                    ps.setInt(5, cmbboxId.getId(constant.TABLE_LIST_POSITION, formArray[4])); // list_pos_id
                    ps.setInt(6, cmbboxId.getId(constant.TABLE_LIST_OFFICE, formArray[5])); // list_off_id
                    ps.setInt(7, cmbboxId.getId(constant.TABLE_LIST_CATEGORY, formArray[6])); // list_cat_id
                    ps.setDate(8, java.sql.Date.valueOf(formArray[7])); // date_hired
                    ps.setInt(9, Integer.parseInt(formArray[8])); // salary
                    ps.execute();

                    ResultSet rs = ps.getGeneratedKeys();
                    if (rs != null && rs.next()) {

                        ps = conn.prepareStatement("INSERT INTO " + constant.TABLE_EMPLOYEE_DETAIL + " ( "
                            + " header_id, date_birth, address_prime, address_other, gender, civil_status, nationality, religion, email, phone_tele, phone_cell, phone_misc, code_SSS, code_TIN, code_GSIS, code_PHIC, code_PAGIBIG) values ((?),(?),(?),(?),(?),(?),(?),(?),(?),(?),(?),(?),(?),(?),(?),(?),(?))", Statement.RETURN_GENERATED_KEYS);

                        ps.setInt(1, rs.getInt(1)); // header_id
                        ps.setDate(2, java.sql.Date.valueOf(formArray[9])); // date_birth
                        ps.setString(3, formArray[10]); // address_prime
                        ps.setString(4, formArray[11]); // address_other
                        ps.setString(5, formArray[12]); // gender
                        ps.setString(6, formArray[13]); // civil_status
                        ps.setString(7, formArray[14]); // nationality
                        ps.setString(8, formArray[15]); // religion
                        ps.setString(9, formArray[16]); // email
                        if(formArray[17].equals("")) { // phone_tele
                            ps.setNull(10, java.sql.Types.INTEGER);
                        } else {
                            ps.setInt(10, (formArray[17].equals("")) ? null : Integer.parseInt(formArray[17]));
                        }
                        if (formArray[18].equals("")) { // phone_cell
                            ps.setNull(11, java.sql.Types.INTEGER);
                        } else {
                            ps.setInt(11, (formArray[18].equals("")) ? null : Integer.parseInt(formArray[18]));
                        }
                        if(formArray[19].equals("")) { // phone_misc
                            ps.setNull(12, java.sql.Types.INTEGER);
                        } else {
                            ps.setInt(12, Integer.parseInt(formArray[19]));
                        }
                        ps.setString(13, formArray[20]); // code_SSS
                        ps.setString(14, formArray[21]); // code_TIN
                        ps.setString(15, formArray[22]); // code_GSIS
                        ps.setString(16, formArray[23]); // code_PHIC
                        ps.setString(17, formArray[24]); // code_PAGIBIG
                        ps.execute();

                    }

                    JOptionPane.showMessageDialog(this, "New Employee Successfully Created.", "SUCCESS", JOptionPane.INFORMATION_MESSAGE);

                    createFormGrid.clearFields();
                    createFormList.clearFields();

                } catch (SQLException | HeadlessException ex) {
                    Logger.getLogger(PanelFrameCreate.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(this, "An Error Occured.", "ERROR", JOptionPane.ERROR_MESSAGE);
                }

            }

        }
    }//GEN-LAST:event_btnSaveActionPerformed

    public void setFrame(JFrame frm) {
        
        this.frame = frm;
        
    }

    public FrameMain getFrame() {
        
        return (FrameMain)this.frame;
        
    }

    public void setButtons(Boolean bool, JToggleButton tButton, Boolean bool2) {
        
        btnFormOptionsGrid.setEnabled(bool);
        btnFormOptionsList.setEnabled(bool);
        
        if (bool == true) {
            btnFormOptionsGrid.setForeground(new Color(25, 25, 25));
            btnFormOptionsList.setForeground(new Color(25, 25, 25));
        } else {
            btnFormOptionsGrid.setForeground(new Color(125, 125, 125));
            btnFormOptionsList.setForeground(new Color(125, 125, 125));
        }
        
        if (bool2 == true) {
            tButton.setSelected(true);
        } else {
            tButton.setSelected(false);
        }
        
    }

    public void loadPanel(final JPanel panel, final int type, final JToggleButton tButton) {
        
        setButtons(false, tButton, true);
        getMainLayout().show(panelMainFormCenter, "Card Load");

        @SuppressWarnings("unchecked")
        SwingWorker<Void, Void> sw = new SwingWorker() {
            @Override
            protected Object doInBackground() throws Exception {
                
                getFrame().progressBar.setString("Loading");
                getFrame().progressBar.setValue(0);
                getFrame().progressBar.setVisible(true);
                getFrame().progressBar.setIndeterminate(true);
                
                try {
                    if (type == constant.PANEL_FRAME) {
                        if (panelFrame == null || panelFrame.isVisible()) {

                            panelMainForm.removeAll();
                            panelFrame = panel;
                            panelMainForm.add(panelFrame);

                        }
                    }

                    getFrame().progressBar.setString("Preparing");
                } catch (Exception ex) {
                    getFrame().progressBar.setString("Failed");
                    System.out.println(ex.getMessage());
                    JOptionPane.showMessageDialog(null, "Error Occured When Loading", "ERROR!", JOptionPane.ERROR_MESSAGE);
                }
                getFrame().progressBar.setString("Initializing");
                return null;
            }
            @Override
            protected void done() {
                new java.util.Timer().schedule(
                    new java.util.TimerTask() {
                        @Override
                        public void run() {

                            getFrame().progressBar.setString("Complete");
                            getFrame().progressBar.setVisible(true);
                            getFrame().progressBar.setValue(100);
                            getFrame().progressBar.setIndeterminate(false);

                            getMainLayout().show(panelMainFormCenter, "Card Form");

                            setButtons(true, tButton, true);

                        }
                    },
                    1000
                );
            }
        };
        
        sw.execute();
        
    }

    private CardLayout getMainLayout() {
        
        CardLayout mainLayout = (CardLayout) panelMainFormCenter.getLayout();
        return mainLayout;
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btFormSwitch;
    private javax.swing.JButton btnClear;
    private javax.swing.JToggleButton btnFormOptionsGrid;
    private javax.swing.JToggleButton btnFormOptionsList;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpload;
    private javax.swing.ButtonGroup createFormSwitch;
    private javax.swing.JDesktopPane jDesktopPane3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelLogo;
    private javax.swing.JLabel lblCenterLoad;
    private javax.swing.JLabel lblImage;
    private javax.swing.JPanel panelAddLeft;
    private javax.swing.JPanel panelAddLeft_Panel01;
    private javax.swing.JPanel panelAddLeft_Panel02;
    private javax.swing.JPanel panelAddLeft_Panel03;
    private javax.swing.JPanel panelButtonLogo;
    private javax.swing.JPanel panelButtons;
    private javax.swing.JPanel panelMain;
    private javax.swing.JPanel panelMainForm;
    private javax.swing.JPanel panelMainFormCenter;
    private javax.swing.JLabel panelMainFormLeft;
    private javax.swing.JLabel panelMainFormLeft1;
    private javax.swing.JLabel panelMainFormLeft2;
    private javax.swing.JPanel panelMainFormLoad;
    private javax.swing.JSeparator panelMainFormSeparator1;
    private javax.swing.JPanel panelNew;
    private javax.swing.JTextField txtfldImg;
    // End of variables declaration//GEN-END:variables

    private JPanel panelFrame;

}
