/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package application;

import classes.ClassConstantsCustom;
import classes.ClassDateFormatValue;
import classes.ClassLabelButton;
import classes.ClassTableButtonEditor;
import classes.ClassTableButtonRenderer;
import classes.ClassTextfieldPrompt;
import classes.ClassTextfieldRequired;
import com.toedter.calendar.JTextFieldDateEditor;
import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author egrubellano
 */
public class PanelEmployeesCreateDependent extends javax.swing.JPanel {

    protected ArrayList<Component> reqList = new ArrayList<>();
    protected Calendar currentDate = Calendar.getInstance();
    protected ClassConstantsCustom constant = new ClassConstantsCustom();
    protected ClassDateFormatValue fmtDateVal = new ClassDateFormatValue();
    protected ClassTextfieldRequired reqField = new ClassTextfieldRequired();
    protected DefaultTableModel dtm;
    protected FramePrime panel_ancestor;
    protected PanelEmployees panel_parent;
    protected PanelEmployeesCreate panel_child;
    protected TableRowSorter<TableModel> sorter;

    /**
     * Creates new form PanelEmployeesCreateDependent
     */
    public PanelEmployeesCreateDependent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelTitle = new javax.swing.JPanel();
        panelFormListTitle_001_caption = new javax.swing.JPanel();
        labelFormListTitle_001_icon = new javax.swing.JLabel();
        labelFormListTitle_001_name = new javax.swing.JLabel();
        panelFormListTitle_001_hr = new javax.swing.JPanel();
        panelFormListTitle_001_breakline = new javax.swing.JSeparator();
        panelMain = new javax.swing.JPanel();
        panelMainCenterForm = new javax.swing.JPanel();
        panelMainCenterFormFields = new javax.swing.JPanel();
        panelFormListField_001 = new javax.swing.JPanel();
        labelFormListField_002_head = new javax.swing.JLabel();
        panelNameFirst = new javax.swing.JPanel();
        labelName = new javax.swing.JLabel();
        txtfldName = new javax.swing.JTextField();
        labelFormListField_002_required = new javax.swing.JLabel();
        panelFormListField_002 = new javax.swing.JPanel();
        labelFormListField_002_head1 = new javax.swing.JLabel();
        labelFormListField_002_required1 = new javax.swing.JLabel();
        dateSelected = new com.toedter.calendar.JDateChooser();
        panelControlsContainer = new javax.swing.JPanel();
        panel_button_sav = new javax.swing.JPanel();
        label_button_sav = new javax.swing.JLabel();
        label_button_clr = new javax.swing.JLabel();
        panelMainCenterView = new javax.swing.JPanel();
        scrollPane = new javax.swing.JScrollPane();
        table_view = new javax.swing.JTable();

        setBackground(new java.awt.Color(245, 245, 245));
        setLayout(new java.awt.BorderLayout());

        panelTitle.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 5, 5, 0));
        panelTitle.setOpaque(false);
        panelTitle.setPreferredSize(new java.awt.Dimension(10, 40));
        panelTitle.setLayout(new java.awt.BorderLayout());

        panelFormListTitle_001_caption.setMinimumSize(new java.awt.Dimension(147, 100));
        panelFormListTitle_001_caption.setOpaque(false);
        panelFormListTitle_001_caption.setPreferredSize(new java.awt.Dimension(199, 100));
        panelFormListTitle_001_caption.setLayout(new java.awt.BorderLayout());

        labelFormListTitle_001_icon.setFont(new java.awt.Font("Century Gothic", 3, 14)); // NOI18N
        labelFormListTitle_001_icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelFormListTitle_001_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_src/icon_16_fingerprint.png"))); // NOI18N
        labelFormListTitle_001_icon.setPreferredSize(new java.awt.Dimension(25, 25));
        panelFormListTitle_001_caption.add(labelFormListTitle_001_icon, java.awt.BorderLayout.LINE_START);

        labelFormListTitle_001_name.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelFormListTitle_001_name.setForeground(new java.awt.Color(25, 25, 25));
        labelFormListTitle_001_name.setText(" Dependent(s) information");
        labelFormListTitle_001_name.setPreferredSize(new java.awt.Dimension(125, 125));
        panelFormListTitle_001_caption.add(labelFormListTitle_001_name, java.awt.BorderLayout.CENTER);

        panelTitle.add(panelFormListTitle_001_caption, java.awt.BorderLayout.LINE_START);

        panelFormListTitle_001_hr.setBorder(javax.swing.BorderFactory.createEmptyBorder(18, 0, 0, 8));
        panelFormListTitle_001_hr.setOpaque(false);
        panelFormListTitle_001_hr.setLayout(new java.awt.GridLayout(0, 1));
        panelFormListTitle_001_hr.add(panelFormListTitle_001_breakline);

        panelTitle.add(panelFormListTitle_001_hr, java.awt.BorderLayout.CENTER);

        add(panelTitle, java.awt.BorderLayout.PAGE_START);

        panelMain.setOpaque(false);
        panelMain.setLayout(new java.awt.BorderLayout());

        panelMainCenterForm.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 5, 5));
        panelMainCenterForm.setOpaque(false);
        panelMainCenterForm.setPreferredSize(new java.awt.Dimension(276, 85));
        panelMainCenterForm.setLayout(new java.awt.BorderLayout());

        panelMainCenterFormFields.setBackground(new java.awt.Color(225, 225, 225));
        panelMainCenterFormFields.setOpaque(false);
        panelMainCenterFormFields.setPreferredSize(new java.awt.Dimension(108, 80));
        panelMainCenterFormFields.setLayout(new java.awt.GridLayout(2, 1));

        panelFormListField_001.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 5, 0));
        panelFormListField_001.setOpaque(false);
        panelFormListField_001.setPreferredSize(new java.awt.Dimension(10, 4));
        panelFormListField_001.setLayout(new java.awt.BorderLayout());

        labelFormListField_002_head.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        labelFormListField_002_head.setForeground(new java.awt.Color(30, 30, 30));
        labelFormListField_002_head.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_src/icon_16_bullet_arrow_right.png"))); // NOI18N
        labelFormListField_002_head.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 3, 0, 0));
        labelFormListField_002_head.setMaximumSize(new java.awt.Dimension(125, 0));
        labelFormListField_002_head.setMinimumSize(new java.awt.Dimension(125, 0));
        labelFormListField_002_head.setPreferredSize(new java.awt.Dimension(20, 0));
        panelFormListField_001.add(labelFormListField_002_head, java.awt.BorderLayout.LINE_START);

        panelNameFirst.setOpaque(false);
        panelNameFirst.setLayout(new java.awt.GridBagLayout());

        labelName.setFont(new java.awt.Font("Century Gothic", 3, 14)); // NOI18N
        labelName.setForeground(new java.awt.Color(50, 50, 50));
        labelName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_src/icon_16_user_silhouette_2.png"))); // NOI18N
        labelName.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        panelNameFirst.add(labelName, gridBagConstraints);

        txtfldName.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txtfldName.setForeground(new java.awt.Color(51, 51, 51));
        txtfldName.setMargin(new java.awt.Insets(2, 5, 2, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        panelNameFirst.add(txtfldName, gridBagConstraints);
        reqList.add(0, txtfldName);

        panelFormListField_001.add(panelNameFirst, java.awt.BorderLayout.CENTER);

        labelFormListField_002_required.setFont(new java.awt.Font("Century Gothic", 3, 14)); // NOI18N
        labelFormListField_002_required.setForeground(new java.awt.Color(255, 0, 0));
        labelFormListField_002_required.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelFormListField_002_required.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/icon_8_bullet_red.png"))); // NOI18N
        labelFormListField_002_required.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        labelFormListField_002_required.setBorder(javax.swing.BorderFactory.createEmptyBorder(-5, 0, 0, 5));
        labelFormListField_002_required.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        labelFormListField_002_required.setPreferredSize(new java.awt.Dimension(15, 15));
        labelFormListField_002_required.setVerifyInputWhenFocusTarget(false);
        panelFormListField_001.add(labelFormListField_002_required, java.awt.BorderLayout.LINE_END);

        panelMainCenterFormFields.add(panelFormListField_001);

        panelFormListField_002.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 5, 0));
        panelFormListField_002.setOpaque(false);
        panelFormListField_002.setPreferredSize(new java.awt.Dimension(10, 4));
        panelFormListField_002.setLayout(new java.awt.BorderLayout());

        labelFormListField_002_head1.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        labelFormListField_002_head1.setForeground(new java.awt.Color(30, 30, 30));
        labelFormListField_002_head1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_src/icon_16_bullet_arrow_right.png"))); // NOI18N
        labelFormListField_002_head1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 3, 0, 0));
        labelFormListField_002_head1.setMaximumSize(new java.awt.Dimension(125, 0));
        labelFormListField_002_head1.setMinimumSize(new java.awt.Dimension(125, 0));
        labelFormListField_002_head1.setPreferredSize(new java.awt.Dimension(20, 0));
        panelFormListField_002.add(labelFormListField_002_head1, java.awt.BorderLayout.LINE_START);

        labelFormListField_002_required1.setFont(new java.awt.Font("Century Gothic", 3, 14)); // NOI18N
        labelFormListField_002_required1.setForeground(new java.awt.Color(255, 0, 0));
        labelFormListField_002_required1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelFormListField_002_required1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/icon_8_bullet_red.png"))); // NOI18N
        labelFormListField_002_required1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        labelFormListField_002_required1.setBorder(javax.swing.BorderFactory.createEmptyBorder(-5, 0, 0, 5));
        labelFormListField_002_required1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        labelFormListField_002_required1.setPreferredSize(new java.awt.Dimension(15, 15));
        labelFormListField_002_required1.setVerifyInputWhenFocusTarget(false);
        panelFormListField_002.add(labelFormListField_002_required1, java.awt.BorderLayout.LINE_END);

        dateSelected.setForeground(new java.awt.Color(51, 51, 51));
        dateSelected.setDateFormatString(" MMMM dd, yyyy");
        dateSelected.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        dateSelected.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_src/icon_16_calendar_red.png")));
        dateSelected.setMaxSelectableDate(currentDate.getTime());
        dateSelected.setOpaque(false);
        panelFormListField_002.add(dateSelected, java.awt.BorderLayout.CENTER);
        reqList.add(1, dateSelected);

        panelMainCenterFormFields.add(panelFormListField_002);

        panelMainCenterForm.add(panelMainCenterFormFields, java.awt.BorderLayout.CENTER);

        panelControlsContainer.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 5, 0));
        panelControlsContainer.setOpaque(false);
        panelControlsContainer.setPreferredSize(new java.awt.Dimension(225, 100));
        panelControlsContainer.setRequestFocusEnabled(false);
        panelControlsContainer.setLayout(new java.awt.GridLayout());

        panel_button_sav.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 5));
        panel_button_sav.setOpaque(false);
        panel_button_sav.setLayout(new java.awt.GridLayout());

        label_button_sav.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        label_button_sav.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_button_sav.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/icon_28_user_male_info.png"))); // NOI18N
        label_button_sav.setText("add dependent");
        label_button_sav.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(159, 159, 159)));
        label_button_sav.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        label_button_sav.setIconTextGap(10);
        label_button_sav.setOpaque(true);
        label_button_sav.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        label_button_sav.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_button_savMouseClicked(evt);
            }
        });
        panel_button_sav.add(label_button_sav);

        panelControlsContainer.add(panel_button_sav);

        label_button_clr.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        label_button_clr.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_button_clr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/icon_28_formheading.png"))); // NOI18N
        label_button_clr.setText("clear fields");
        label_button_clr.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(159, 159, 159)));
        label_button_clr.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        label_button_clr.setIconTextGap(10);
        label_button_clr.setOpaque(true);
        label_button_clr.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        label_button_clr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_button_clrMouseClicked(evt);
            }
        });
        panelControlsContainer.add(label_button_clr);

        panelMainCenterForm.add(panelControlsContainer, java.awt.BorderLayout.LINE_END);

        panelMain.add(panelMainCenterForm, java.awt.BorderLayout.PAGE_START);

        panelMainCenterView.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 5, 15, 5));
        panelMainCenterView.setOpaque(false);
        panelMainCenterView.setLayout(new java.awt.CardLayout());

        scrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        table_view.setBackground(new java.awt.Color(245, 245, 245));
        table_view.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        table_view.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table_view.setFillsViewportHeight(true);
        table_view.setGridColor(new java.awt.Color(230, 230, 230));
        table_view.setRowHeight(30);
        table_view.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        table_view.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                table_viewMouseReleased(evt);
            }
        });
        scrollPane.setViewportView(table_view);

        panelMainCenterView.add(scrollPane, "card2");

        panelMain.add(panelMainCenterView, java.awt.BorderLayout.CENTER);

        add(panelMain, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    public void initAdditionalComponents(PanelEmployeesCreate panel_create) {
        
        setFrameChild(panel_create);
        
        setPlaceHolder();
        
        reqField.requiredFieldsInitialize(reqList);
        
        dateSelected.getComponent(0).setBackground(new Color(180, 180, 180));
        txtfldName.setBackground(Color.WHITE);
        
        panel_parent.lbl_btn.addClass(label_button_sav, constant.BUTTON_BG_COLOR_PRESS_BLUE, constant.BUTTON_BG_COLOR_NEW_BLUE, constant.BUTTON_BG_COLOR_OLD, constant.BUTTON_FG_COLOR_NEW, constant.BUTTON_FG_COLOR_OLD);
        panel_parent.lbl_btn.addClass(label_button_clr, constant.BUTTON_BG_COLOR_PRESS_BLUE, constant.BUTTON_BG_COLOR_NEW_BLUE, constant.BUTTON_BG_COLOR_OLD, constant.BUTTON_FG_COLOR_NEW, constant.BUTTON_FG_COLOR_OLD);
        
        JTextFieldDateEditor dateTextEditor = (JTextFieldDateEditor) dateSelected.getDateEditor();
        dateTextEditor.setEditable(false);
        dateTextEditor.setHorizontalAlignment(JTextField.CENTER);
        
        initTable();
        
    }

    private void table_viewMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_viewMouseReleased

//        if (evt.getButton() == 3 && table_view.getSelectedRow() >= 0) {
//            popupMenu.show(table_view, (int)evt.getX(), (int)evt.getY());
//        }

    }//GEN-LAST:event_table_viewMouseReleased

    private void label_button_savMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_button_savMouseClicked

        if (reqField.requiredFieldsValidate(reqList)) {
            ArrayList<Object> addNewRow = new ArrayList<>();
            addNewRow.add("");
            addNewRow.add(txtfldName.getText().trim().substring(0, 1).toUpperCase() + txtfldName.getText().trim().substring(1));
            addNewRow.add(fmtDateVal.formatDateToString(dateSelected).trim());
            addNewRow.add("");
            dtm.addRow(addNewRow.toArray());

            table_view.setModel(dtm);
            sorter = new TableRowSorter<TableModel>(dtm);
            sorter.setSortable(0, false);
            sorter.setSortable(3, false);
            table_view.setRowSorter(sorter);

            dateSelected.setDate(null);
            txtfldName.setText("");
            txtfldName.requestFocus();
        }

    }//GEN-LAST:event_label_button_savMouseClicked

    private void label_button_clrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_button_clrMouseClicked

        dateSelected.setDate(null);
        txtfldName.setText("");
        txtfldName.requestFocus();

    }//GEN-LAST:event_label_button_clrMouseClicked

    /**
     * Get table model.
     * @return table_view
     */
    public JTable getTableModel() {
        
        return table_view;
        
    }

    /**
     * Set table model.
     * @param tbl
     */
    public void setTableModel(JTable tbl) {
        
        clearDialog();
        sorter = new TableRowSorter<TableModel>(dtm);
        sorter.setSortable(0, false);
        sorter.setSortable(3, false);
        table_view.setRowSorter(sorter);
        
        for (int i = 0; i < tbl.getRowCount(); i++) {
            ArrayList<Object> addNewRow = new ArrayList<>();
            addNewRow.add(tbl.getValueAt(i, 0));
            addNewRow.add(tbl.getValueAt(i, 1));
            addNewRow.add(tbl.getValueAt(i, 2));
            addNewRow.add(tbl.getValueAt(i, 3));
            dtm.addRow(addNewRow.toArray());
        }
        
        table_view.setModel(dtm);
        
    }

    /**
     * Clear all dialog fields.
     */
    public void clearDialog() {
        
        DefaultTableModel tm = (DefaultTableModel)table_view.getModel();
        tm.getDataVector().removeAllElements();
        table_view.setModel(tm);
        table_view.repaint();
        txtfldName.setText("");
        txtfldName.requestFocus();
        dateSelected.setDate(null);
        
    }

    /**
     * Refresh all dialog fields.
     */
    public void refreshDialog() {
        
        table_view.repaint();
        txtfldName.setText("");
        txtfldName.requestFocus();
        dateSelected.setDate(null);
        
    }

    public void setPlaceHolder() {
        
        ClassTextfieldPrompt tpTxtfldName = new ClassTextfieldPrompt("Enter a Name", txtfldName);
        JTextFieldDateEditor dateTextEditor = (JTextFieldDateEditor) dateSelected.getDateEditor();
        ClassTextfieldPrompt tpTxtfldDate = new ClassTextfieldPrompt("Select a Date", dateTextEditor);
        tpTxtfldDate.setHorizontalAlignment(JTextField.CENTER);
        
        ClassTextfieldPrompt[] placeholder = {
            tpTxtfldName,
            tpTxtfldDate
        };
        
        // adjust display
        for (ClassTextfieldPrompt placeholder1 : placeholder) {
            placeholder1.changeAlpha(0.3f);
            placeholder1.changeStyle(Font.ITALIC);
        }
        
    }

    public void resetLabelButtons() {

        label_button_sav.setBackground(constant.BUTTON_BG_COLOR_OLD);
        label_button_sav.setForeground(constant.BUTTON_FG_COLOR_OLD);
        label_button_clr.setBackground(constant.BUTTON_BG_COLOR_OLD);
        label_button_clr.setForeground(constant.BUTTON_FG_COLOR_OLD);
    }

    private void setFrameChild(PanelEmployeesCreate child_value) {

        this.panel_child = child_value;
        setFrameParent(this.panel_child.panel_parent);
        setFrameAncestor(this.panel_parent.panel_ancestor);
        setFrameConstants(this.panel_ancestor.constant);
    }

    private void setFrameParent(PanelEmployees parent_value) {

        this.panel_parent = parent_value;
    }

    private void setFrameAncestor(FramePrime ancestor_value) {

        this.panel_ancestor = ancestor_value;
    }

    private void setFrameConstants(ClassConstantsCustom constant_value) {

        this.constant = constant_value;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser dateSelected;
    private javax.swing.JLabel labelFormListField_002_head;
    private javax.swing.JLabel labelFormListField_002_head1;
    private javax.swing.JLabel labelFormListField_002_required;
    private javax.swing.JLabel labelFormListField_002_required1;
    private javax.swing.JLabel labelFormListTitle_001_icon;
    private javax.swing.JLabel labelFormListTitle_001_name;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel label_button_clr;
    private javax.swing.JLabel label_button_sav;
    private javax.swing.JPanel panelControlsContainer;
    private javax.swing.JPanel panelFormListField_001;
    private javax.swing.JPanel panelFormListField_002;
    private javax.swing.JSeparator panelFormListTitle_001_breakline;
    private javax.swing.JPanel panelFormListTitle_001_caption;
    private javax.swing.JPanel panelFormListTitle_001_hr;
    private javax.swing.JPanel panelMain;
    private javax.swing.JPanel panelMainCenterForm;
    private javax.swing.JPanel panelMainCenterFormFields;
    private javax.swing.JPanel panelMainCenterView;
    private javax.swing.JPanel panelNameFirst;
    private javax.swing.JPanel panelTitle;
    private javax.swing.JPanel panel_button_sav;
    private javax.swing.JScrollPane scrollPane;
    public javax.swing.JTable table_view;
    private javax.swing.JTextField txtfldName;
    // End of variables declaration//GEN-END:variables

    
    private void initTable() {
        
        ImageIcon icon = new javax.swing.ImageIcon(getClass().getResource("/img_src/icon_16_delete.png"));
        
        ClassTableButtonRenderer buttonTableRender = new ClassTableButtonRenderer(icon, Color.WHITE, Color.WHITE, Color.WHITE);
        ClassTableButtonEditor buttonTableEditor = new ClassTableButtonEditor(icon, Color.WHITE, Color.WHITE, Color.WHITE){

            // Override with custom table row delete.
            @Override
            protected void fireEditingStopped() {
                DefaultTableModel tm = (DefaultTableModel)table_view.getModel();
                tm.removeRow(table_view.convertRowIndexToModel(table_view.getSelectedRow()));

                table_view.setModel(tm);
                table_view.repaint();
            }
            
        };
        buttonTableEditor.setTable(table_view); // Set-up table update button

        this.dtm = new DefaultTableModel(){
            @Override
            public Class getColumnClass(int column){
                Class returnValue;
                try {
                    if((column>=0) && (column<getColumnCount()) && (column!=2)) {
                        returnValue = getValueAt(0, column).getClass();
                    } else {
                        returnValue = Object.class;
                    }
                } catch (Exception ex) {
//                    System.out.println(ex.getMessage());
                    returnValue = Object.class;
                }
                return returnValue;
            }
            @Override
            public boolean isCellEditable(int row, int column) {
                switch(column) {
                    case 3:
                        return true;
                    default:
                        return false;
                }
            }
        };
        
        ArrayList<Object> columnTitle = new ArrayList<>();
        
        columnTitle.add("");
        columnTitle.add("DEPENDENT'S NAME");
        columnTitle.add("DATE");
        columnTitle.add("");
        
        dtm.setDataVector(null, columnTitle.toArray());

        table_view.setRowHeight(35);
        table_view.setModel(dtm);
        table_view.setSelectionBackground(constant.ROW_BG_COLOR_SELECT_DEFAULT);
        table_view.setFont(new Font("Tahoma", Font.PLAIN, 11));
        scrollPane.setViewportView(table_view);

        // Create & set table sorter
        sorter = new TableRowSorter(dtm);
        sorter.setSortable(1, false);
        sorter.setSortable(2, false);
        table_view.setRowSorter(sorter);

        // Turn OFF user ability to re-order columns
        table_view.getTableHeader().setReorderingAllowed(false);
        
        table_view.getColumnModel().getColumn(0).setMinWidth(0);
        table_view.getColumnModel().getColumn(0).setMaxWidth(0);
        table_view.getColumnModel().getColumn(0).setResizable(false);
        table_view.getColumnModel().getColumn(0).setPreferredWidth(0);
        table_view.getColumnModel().getColumn(1).setMinWidth(243);
        table_view.getColumnModel().getColumn(3).setMinWidth(80);
        table_view.getColumnModel().getColumn(3).setMaxWidth(80);
        table_view.getColumnModel().getColumn(2).setPreferredWidth(80);
        table_view.getColumnModel().getColumn(2).setResizable(true);
        table_view.getColumnModel().getColumn(3).setMinWidth(35);
        table_view.getColumnModel().getColumn(3).setMaxWidth(35);
        table_view.getColumnModel().getColumn(3).setPreferredWidth(35);
        table_view.getColumnModel().getColumn(3).setCellEditor(buttonTableEditor);
        table_view.getColumnModel().getColumn(3).setCellRenderer(buttonTableRender);
        table_view.getColumnModel().getColumn(3).setResizable(false);
        table_view.setFillsViewportHeight(true);
        
        JTableHeader th = table_view.getTableHeader();
        th.setFont(new Font("Century Gothic", Font.BOLD, 13));
        
        DefaultTableCellRenderer renderHeaderCenter = (DefaultTableCellRenderer)table_view.getTableHeader().getDefaultRenderer();
        renderHeaderCenter.setHorizontalAlignment(JLabel.CENTER);
        table_view.getColumnModel().getColumn(1).setHeaderRenderer(renderHeaderCenter);
        
        DefaultTableCellRenderer renderCellLeft = new DefaultTableCellRenderer();
        renderCellLeft.setHorizontalAlignment(SwingConstants.LEFT);
        table_view.getColumnModel().getColumn(1).setCellRenderer(renderCellLeft);
        
        DefaultTableCellRenderer renderCellCenter = new DefaultTableCellRenderer();
        renderCellCenter.setHorizontalAlignment(SwingConstants.CENTER);
        table_view.getColumnModel().getColumn(2).setCellRenderer(renderCellCenter);
        
    }

}
